### ISSUE TITLE
Stream interface

### ISSUE THREAD

**Issue by gtramontina** [amqp-node/amqplib#106]
Is there any built-in support for actual streaming?
I mean, connect, get a channel and pipe stdin in, for example...

Thanks!

**Comment by squaremo** [comment]
Hi @gtramontina, are you still interested in this idea, and did you look at rabbit.js?

**Comment by rightaway** [comment]
rabbit.js looks like it's unmaintained. I'm interested in streams, but as a consumer. So piping items from the queue out of RabbitMQ.
