### ISSUE TITLE
How to catch timeout error

### ISSUE THREAD

**Issue by ssured** [amqp-node/amqplib#127]
Hi,

Thanks for the library.

After disconnecting and reconnecting the network I get the following error:

```
Error: read ETIMEDOUT
  at errnoException (net.js:904:11)
  at TCP.onread (net.js:558:19)
```

Using the Promise example code on the main README

```
var q = 'tasks';

var open = require('amqplib').connect('amqp://localhost');

// Consumer
open.then(function(conn) {
  var ok = conn.createChannel();
  ok = ok.then(function(ch) {
    ch.assertQueue(q);
    ch.consume(q, function(msg) {
      if (msg !== null) {
        console.log(msg.content.toString());
        ch.ack(msg);
      }
    });
  });
  return ok;
}).then(null, console.warn);
```

Is there a way to restart the connection, how should I handle that? I cannot find a connection error handler in the docs.

Thanks!

**Comment by squaremo** [comment]
When you say "disconnecting and reconnecting the network" do you mean mean something like pulling out the ethernet cable and plugging it back in (or the near equivalent)?

**Comment by ssured** [comment]
I have AMQP running on my development macbook. I am in an environment where the wifi is not stable, so yeah this is caused by network issues.
I added a heartbeat of 10 seconds and now the setup is much more stable, but adding the heartbeat does not feel like a fix for me.

**Comment by ssured** [comment]
Excuse me, I am a little unclear here; amqp.node is running from my macbook (dev env) to a stable AMQP server running on Digital Ocean.

**Comment by cressie176** [comment]
Closing as very old. For anyone else who reads this issue a rough process would be...

1. Listen for connection/channel error and close events
2. When an even occurs re-establish the connection, channels and subscribers
3. Be very careful about concurrency issues since it's likely that some of your code may  still attempt to use the broken channel or connections
