### ISSUE TITLE
Publish as a Meteor package

### ISSUE THREAD

**Issue by orlade** [amqp-node/amqplib#134]
The Meteor community could really benefit from a packaged version of amqp.node. There is an existing Meteor package that simply wraps `node-amqp`, but this library is far nicer to use.

I'm not too familiar with the new packaging system, but [here's an example](https://github.com/DSpeichert/meteor-amqp) of a simple wrapping of node-amqp for Meteor. With a properly-declared `package.js`, this would easily be the best AMQP package for Meteor.

For those wondering in the meantime, this library still works well via [`Meteor.requireNpm`](https://atmospherejs.com/meteorhacks/npm), but it's more of a hassle to work that out in the first place.

**Comment by squaremo** [comment]
> For those wondering in the meantime, this library still works well via Meteor.requireNpm, but it's more of a hassle to work that out in the first place.

Would adding a note in the README/elsewhere help with this?
