### ISSUE TITLE
WaitForConfirm issue after publish is invoked 

### ISSUE THREAD

**Issue by richzw** [amqp-node/amqplib#141]
I try to get the error information after `publish` is invoked with `promise`

``` javascript
    function publishCallback(err, ok) {
        if (err !== null)
            return when.reject( new Error('Sender: publish message error found') );
    }   

    ch.publish( this.ex_, key, msg, { deliveryMode: 2, mandatory: true }, publishCallback);
    return ch.waitForConfirms()
        .then(function() {
            console.log('Sender: publish message processed');
        }, function(err) {
            return when.reject( new Error('Sender: Publish Message Error') );
        });
```

If the channel is OK, the `Sender: publish message processed` can be shown in log.
However, if the channel is failed, I can not get any error information.

Could someone help me figure out the reason of it?

**Comment by squaremo** [comment]
What happens if you put a log message in the `function(err){ ... }` bit?

**Comment by richzw** [comment]
Here the errors I got

```
Error: Connection closed: 320 (CONNECTION-FORCED) with message "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"

Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19)
```

**Comment by michaelklishin** [comment]
@richzw "reason 'shutdown'" means that RabbitMQ was instructed to shut down. Are you intentionally doing this to imitate a failure?

**Comment by richzw** [comment]
@michaelklishin yes, I try to start and stop RabbitMQ randomly to imitate a failure.

I hope my app can handle this connection exception...

**Comment by richzw** [comment]
Here are some details of my apps.

I have one class `Sender`, and once the connection fails, then retry to connect to amqp after one fixed delay time until the connection success. 

```javascript
Sender.prototype.retryConnect_ = function( err ) {
	console.error('Sender: MessageBus disconnected, attempted to reconnect. Err:' + err);

	return when( this.handldConnectionException_() )
		.with( this )
		.delay( this.retryDelay_ )
		.then( function() { 
			return this.tryConnect_();
		})
		.catch( function( e ) {
			console.log('Sender: [Err] connection error ' + e);
			return this.tryConnect_();
		});

};

Sender.prototype.tryConnect_ = function() {
	return when(amqp.connect( this.addr_ ))
		.with( this )
		.then( this.createChannel_ )
		.then( this.createExchange_ )
		.then( this.handleChannelError_ )		
		.then( this.handleDisconnections_ )			
		.then( this.handleUnrouteableMessages_ )
		.then( this.handleClose_ )
		.then( this.handleChannelClose_ )
		.catch( function( e ) {
			return this.retryConnect_( e );
		});
};
```

On the other side, whenever there are messages to be sent, just call `deliverMessage`. In this function, first check whether the connection is ok or not, if ok, then call `publish`. otherwise, callback function will be invoked here.

```javascript
Sender.prototype.getConnection_ = function() {
	if ( this.ch_ === null ) {
		return when.reject( new Error('Sender: Message bus connection failed now') );
	} else {
		return when.resolve( this.ch_ );
	}
};

Sender.prototype.publish_ = function( channel, key, msg ) {
	channel.publish( this.ex_, key, msg, { deliveryMode: 2, mandatory: true });

	return channel.waitForConfirms()
		.then(function() {
			console.log('Sender: publish message processed');
		}, function(err) {
			console.log('[Error] Sender: publis message ' + err );
			return when.reject( new Error('Sender: Publish Message Error') );
		});
};

Sender.prototype.deliverMessage = function ( key, msg ) {
	return this.getConnection_()
		.with( this )
		.then( function( channel ) { 
			this.publish_( channel, key, msg ); 
		})
		.catch( function( err ) {
			this.cb_( key );
		});
};
```

Details of those codes, please find in this [link](https://gist.github.com/richzw/8ef4cfbf3bb7fc86158e)

**Comment by squaremo** [comment]
> Sorry for this long post.

Lots of relevant information is *never* a problem! Thank you for being thorough.

It sounds like this:

> we can see that the exception ECONNRESET can be caught some time, however, it can NOT be caught by error event in some special case

is the (main) cause of your problems. I will try to make an example with the same problem, so I can figure out where the bug is.

**Comment by richzw** [comment]
After I change some code sequence as below:

```javascript
Sender.prototype.tryConnect_ = function() {
	return when( this.createConnection_() )
		.with( this )
		.then( this.handleConnectionError_ )
		.then( this.createChannel_ )
		.then( this.handleChannelError_ )
		.then( this.createExchange_ )
		.then( this.handleUnrouteableMessages_ )
		//.then( this.handleConnectionClose_ )
		//.then( this.handleChannelClose_ )
		.catch( function( e ) {
			return this.retryConnect_( e );
		});
```

It seems that works well, when I stop and start the `rabbitmq` service randomly. And those errors can be caught in the `error` event. 

Anyway, I will try to test under other cases to ensure the code robust...

**Comment by spencerapplegate** [comment]
@squaremo is there any resolve on this? I am having the same issue

**Comment by jaroslavl1** [comment]
From my internal testing waitForConfirms and channel.publish with confirmation callback on a confirm channel are not functional. When I stop RabbitMQ in the middle of my test before publish executes both the publish callback and waitForConfirms succeed without error. Using amqplib 0.4.0

**Comment by Matthew-Davey** [comment]
This is still the case in 0.4.1

**Comment by cressie176** [comment]
I think there may be a misunderstanding about `waitForConfirms`.

It will success if all published messages are confirmed, or reject if any are explicitly not acknowledged by the broker, or wait indefinitely for the missing confirmations. However, I do not believe it will reject when a channel or connection error is emitted.
