### ISSUE TITLE
Do not propagate 'error' event when using promise API

### ISSUE THREAD

**Issue by xytis** [amqp-node/amqplib#142]
I had an issue with `assertQueue` borking down whole connection, similar to https://github.com/squaremo/amqp.node/issues/108.

Core reason is the same as You stated in final comment: 'error' event is bubbled to default event handler (it was captured by `connection.on('error',...)` in my case). I 'hacked' this by registering per channel 'error' event handler, but this seems to be problematic because that handler has no domain knowledge about error origin and may do nothing to handle it (apart from logging).
The promise returned by `assertQueue` already triggers the code which handles (or ignores) the failure.

Is it possible _not_ to propagate 'error' event when promise is rejected with an error?

**Comment by squaremo** [comment]
I see what you're getting at, I think -- there's no reason to have the error event when the promise is rejected. There are reasons other than a failed operation for the server to close a channel, but perhaps they could be segregated into

 * failed operation -> reject promise
 * server-initiated close -> close event
 * other problem -> error event

For the minute, does it matter (apart from aesthetically) if there's a no-op error handler on the channel/connection, as well as the promise rejection handler?

**Comment by xytis** [comment]
Disregarding clarity and aesthetics it does not matter if I capture `'error'` event on channel AND handle the rejected promise. But in general, main reason why I would like to get rid of the `'error'` event here, is that the handler most commonly will not have enough contextual information to actually handle the error (i.e. retry last operation). Another problem, which is annoying, is that unhandled `'error'` bubbles up to connection, and closes it down.

**Comment by mateodelnorte** [comment]
+1 That an uncaught error should not bubble to connection and cause a close. We're dealing with this same behavior by adding workarounds in our code.
