### ISSUE TITLE
memory leak Promise API example

### ISSUE THREAD

**Issue by mike-aungsan** [amqp-node/amqplib#147]
I run Promise API example and insert 100, 1000, and 3000 at a time. Memory grow up to 1GB

**Comment by squaremo** [comment]
Would you post example code please?

**Comment by puncha** [comment]
I also encounter this issue. I created an infinite loop which simply keeps on publishing messages to queue. After 12 hours, the memory grow up to 1GB.

**Comment by ken107** [comment]
My process gets killed by the kernel after a while because run out of memory.  I'm going to try rewrite using callbacks and hopefully not have to deal with this.

Honestly only obsessive compulsive people should be in charge of creating frameworks for other people to use.  I have so little trust in other people's code nowadays.

**Comment by cressie176** [comment]
Running the example using setInterval to create a loop seems to work OK. I'm limiting the heap size to bring on any starvation issues early with `node --max_old_space_size=128 index.js` 

```
var q = 'tasks';

var open = require('amqplib').connect('amqp://localhost');

// Publisher
open.then(function(conn) {
  return conn.createChannel();
}).then(function(ch) {
  return ch.assertQueue(q).then(function(ok) {
    setInterval(function() {
      ch.sendToQueue(q, new Buffer('something to do'));
    }, 1);
  });
}).catch(console.warn);

// Consumer
open.then(function(conn) {
  return conn.createChannel();
}).then(function(ch) {
  return ch.assertQueue(q).then(function(ok) {
    return ch.consume(q, function(msg) {
      if (msg !== null) {
        console.log(msg.content.toString());
        ch.ack(msg);
      }
    });
  });
}).catch(console.warn);
```

No issues after 20 minutes

**Comment by cressie176** [comment]
Could the problem be related to how you're publishing? Obviously publishing takes some time, and until the message is sent, it will consume some memory. If you're attempting to publishing a large number of documents without any kind of back pressure or throttling you'll eventually run out of memory.

**Comment by ken107** [comment]
I have modified my code to use the callback_api and the process is stable now, it's now hovering around 140m for the last 6 hours.  I just wrap `util.promisify` around all the API calls.  But I had to do like `util.promisify(ch.assertQueue.bind(ch))`.  Sorry if I was a little frustrated there.

**Comment by svyatogor** [comment]
I had exact same problem when doing `publish` on the channel. Switching to callback API solved the problem.

**Comment by cressie176** [comment]
I updated my test script as follows...

```js
const random = require('random-readable');
const amqplib = require('amqplib');

(async () => {
  const connection = await amqplib.connect('amqp://localhost');
  const channel = await connection.createChannel();
  await channel.assertQueue('test');

  const stream = random
    .createRandomStream()
    .on('error', console.error)
    .on('data', (data) => {
      const ok = channel.sendToQueue('test', data);
      if (!ok) {
        console.log('pausing');
        stream.pause();
      }
    })
    .on('end', () => {
      console.log('end');
    });

  channel.on('drain', () => {
    console.log('resuming');
    stream.resume();
  })
})();
```

I ran this with limited memory for several minutes and node maxed out at around 64mb but did not error. When I commented out the pause when publish indicates that the buffer is full, I will quickly ran out of memory (as expected). This suggests there is (no longer) a memory leak publishing messages using the promise API.
