### ISSUE TITLE
How to get error code in channel.on('error') ?

### ISSUE THREAD

**Issue by hippich** [amqp-node/amqplib#149]
I need to react to specific errors. I could parse error text, but I wonder if it is possible to read code (i.e. 404, 405, etc)

**Comment by squaremo** [comment]
I guess the error code could be put in an expando property. Fancy giving it a go?

**Comment by hippich** [comment]
not sure what you meant by 'expando property' and do you mean if i should try to submit PR by your 'fancy giving it a go'? :)

**Comment by squaremo** [comment]
Heh, yeah that was pretty archaic .. I just mean property. Yes, PRs very welcome -- I'm quite busy at the minute (plus nice to have other people involved)

**Comment by hippich** [comment]
Yeah, no problem, will do it!

**Comment by cressie176** [comment]
Closing as PR was merged.
