### ISSUE TITLE
inconsistency in assertQueue() exception catching

### ISSUE THREAD

**Issue by ghost** [amqp-node/amqplib#154]
i have "myqueue" configured with options {durable:true, expires:1800000}

if i try to assert Queue with the following code

ch.assertQueue('myqueue', function(err, ok) {
      if (err) return console.error('Error:', err);
      [...some other code...]
}):

> > > exception 'err' is not caught by my code, whereas it should be since queues defaults are {durable:false, expires:unset}. Instead an exception is caught in event.js at line 85:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - inequivalent arg 'x-expires' for queue 'mqtt-subscription-worker-qos1' in vhost '/': received none but current is the value '1800000' of type 'long'"

but: if i modify the code as below (example):

ch.assertQueue('myqueue', {durable:false}, function(err, ok) {
      if (err) return console.error('Error:', err);
      [...some other code...]
}):

> > > then exception 'err' is caught and the console reads:

Error: [Error: Operation failed: QueueDeclare; 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - inequivalent arg 'x-expires' for queue 'mqtt-subscription-worker-qos1' in vhost '/': received none but current is the value '1800000' of type 'long'"]

**Comment by squaremo** [comment]
This version:

```
ch.assertQueue('myqueue', function(err, ok) {
  if (err) return console.error('Error:', err);
  [...some other code...]
});
```

supplies the callback in the position of the `options` argument, so it won't be called on error (or success for that matter).

**Comment by squaremo** [comment]
@carbip Did you try changing the position of the callback argument? (e.g., by supplying `{}` as the options argument)
