### ISSUE TITLE
ECONNRESET on consumer in Azure

### ISSUE THREAD

**Issue by Recodify** [amqp-node/amqplib#160]
I've actually solved this issue now, and it's not a problem with your code, but it stumped me for a number of days so thought it might be worth sharing:

http://stackoverflow.com/questions/30731181/econnreset-on-node-js-rabbitmq-consumer-in-azure/30731383#30731383

**Comment by squaremo** [comment]
Good thinking, thank you for posting it here. I ought to spend more time on stackoverflow!

Do you think I should make a note in the docs about heartbeats and load-balancing? I think some other AMQP libraries have a default of just < 5min, for this reason.

**Comment by ajay67** [comment]
+1

**Comment by syberkitten** [comment]
Having the same Issue while running a consumer on window
to a rabbitMQ version 3.1.5

I'm able to consume messages but after a minute or so,
the process crashes getting this error:
events.js:85
      throw er; // Unhandled 'error'
            ^
Error: read ECONNRESET
    at exports._errnoException (util
    at TCP.onread (net.js:559:26)

Is this a rabbit issue? will a newer version such as 3.5.3 won't have this issue?

**Comment by syberkitten** [comment]
Update, I've applied the solution provided here, with the heartbeat "?heartbeat=5"

It lasts much longer, but eventually i got the following error:
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Unexpected close
    at succeed (c:\Development\nodejs\wos\node_modules\amqplib\lib\connection.js:270:13)
    at onOpenOk (c:\Development\nodejs\wos\node_modules\amqplib\lib\connection.js:252:5)
    at c:\Development\nodejs\wos\node_modules\amqplib\lib\connection.js:165:32
    at c:\Development\nodejs\wos\node_modules\amqplib\lib\connection.js:159:12
    at Socket.recv (c:\Development\nodejs\wos\node_modules\amqplib\lib\connection.js:495:12)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at readableAddChunk (_stream_readable.js:174:11)

Is there something I'm missing here?

**Comment by DominicCabral** [comment]
+1

**Comment by cressie176** [comment]
Closing as very old now, and most likely an environmental issue.
