### ISSUE TITLE
Promises and emiting event

### ISSUE THREAD

**Issue by jgato** [amqp-node/amqplib#174]
I have some doubts about the best way of using promises and managing future events, after the promise has been resolved:

http://stackoverflow.com/questions/31802221/nodejs-best-practices-with-promises/31802437#31802437

For example with amqp.node library, I can subscribe a queue and the promise will let me know if it was ok, or something wrong happened. But, after resolving the promise, if I want to detect things like queue-deleted, connection-close, etc, etc... I have to add eventlisteners to the connection object. 

What is your opinion about that?

**Comment by cressie176** [comment]
Closing as very old (and lots of other discussions about promises vs events)
