### ISSUE TITLE
ConfirmChannel doesn't support Promise mode for publish?

### ISSUE THREAD

**Issue by jwalton** [amqp-node/amqplib#179]
Maybe I'm missing something, but at a glance it looks like [ConfirmChannel.publish()](https://github.com/squaremo/amqp.node/blob/3f6e41e12d20c504ef46cef4a576bd78b7b4e63b/lib/channel_model.js#L298) doesn't return a Promise like most other methods that accept a callback?  Is this because it returns `true` or `false` like `Channel.publish()`?

**Comment by squaremo** [comment]
Yes, exactly. It was a tricky choice, but I wanted to support flow control, and there's no good alternative.

**Comment by jcready** [comment]
My solution to this problem was to modify the ConfirmChannel's `publish()` method to return a promise with an additional `ok` property on it.

```js
function promisifyPublish(channel){
  // This wrapper will modify the channel's `publish` and `sendToQueue` methods
  // to return a promise that contains one extra property: `ok`
  // 
  // This `ok` value is the result of the underlying `.write()` call and should
  // allow you to make intelligent flow control decisions.

  var publish = channel.publish;
  channel.publish = publishMessage;
  return channel;

  function publishMessage(exchange, key, msg, options){
    // So we create two outer variables:
    // - ok (the boolean value of the underlying `.write()` call)
    // - write (the special promise we return)
    //
    // We do this because the value of `ok` is dependent on the result of
    // something happening inside the scope of the Promise initialization.
    // We need to hold onto this value until the promise has actually been
    // assigned to a variable so that we may assign the `ok` property on it.
    var ok, write = new Promise(function(resolve, reject){
      // Simple promisification callback: rejects if there was an error,
      // otherwise it resolves.
      var callback = function(err){ return err ? reject(err) : resolve() };

      // Make sure we have an object to pass to the original `publish`
      var opts = options || {};

      // ** Here be dragons. **
      // This is probably too clever for its own good, but it's the magic
      // part where we set that outer `ok` variable to the result of the call
      // to the original `channel.publish()` (e.g. the underlying `.write()`)
      ok = publish.call(channel, exchange, key, msg, opts, callback);
    });

    // Finally we set the special `ok` property on the promise and return it.
    write.ok = ok;
    return write;
  }
}
```

Then I use it like this:

```js
amqp.connect(url)
  .then(createChannel)
  .then(promisifyPublish)
  .then(function(channel){
    var sent = channel.sendToQueue('someQueue', 'Hello World!');
    if (sent.ok) {
      // continue sending
    } else {
      // maybe pause sending until unblocked?
      channel.once('drain', function(){
        // continue sending
      });
    }
  });

function createChannel(connection){
  return connection.createConfirmChannel();
}
```

**Comment by jwalton** [comment]
@squaremo Oh...  In [amqp-connection-manager](https://github.com/benbria/node-amqp-connection-manager), I made it so I return the `true` or `false` via the Promise...  You've just made me realize I am not smart.  :P

Hmm... @jcready 's `ok` solution was one I was going to suggest.  You could also return a `{promise, ok}` object (which works nicely with destructuring assignments.)  The other thing that comes to mind would be to add a `bufferFull` variable on the channel so you could do something like:

    if channel.bufferFull
        // Wait for drain event to send
    else
        // Send now

And then you could return a promise.  These are all suboptimal for different reasons, though.  :/  Is there one of these you especially like?  I have a feeling I'm going to be bumping the major version on amqp-connection-manager on Monday.  :P

**Comment by jaroslavl1** [comment]
this is annoying and strangely node.call from when.js doesn't work on it too and ends up with long strange exception. Fortunately converting it to promisified version is quite easy

**Comment by squaremo** [comment]
> this is annoying and strangely node.call from when.js doesn't work on it too and ends up with long strange exception

@jaroslavl1 That *is* strange! Do you mind posting the exception to a gist, if you can provoke it again?

> These are all suboptimal for different reasons, though. :/

Thinking about it, either of the solutions above is not so bad if you do something like

```js
var p;
do {
  p = ch.publish(...);
  // something with p
} while (p.ok);
```

I pushed a branch https://github.com/squaremo/amqp.node/tree/confirm_promise_return which implements this (the "add .ok to a promise, which is then returned" solution). There's an example in https://github.com/squaremo/amqp.node/blob/confirm_promise_return/examples/confirmChannel.js

What do you think?

**Comment by jcready** [comment]
:feelsgood: :+1:

**Comment by chaddjohnson** [comment]
@squaremo Thank you for the wonderful library.

The [documentation](http://www.squaremobius.net/amqp.node/channel_api.html#channel_publish) appears to say that the `channel#publish` method returns a promise, and in my experience, it does not. For me it returns `true`.

Perhaps the documentation should be updated for this (and potentially other) methods?

**Comment by jcready** [comment]
Read the last paragraph in the section you linked to.

**Comment by chaddjohnson** [comment]
@jcready Thank you; that clears things up a bit.

However, I still find it confusing that that section says "Promises or callbacks" at the top in bold. To me, this says this function may return a promise if the promise-based version of the library is used and that a callback can be passed if the callback-based version of the library is used.

**Comment by jwalton** [comment]
@chaddjohnson I shall pimp my library.  :)  If you use [amqp-connection-manager](https://github.com/benbria/node-amqp-connection-manager) to setup your connection to the DB, then the ChannelWrapper you get back does indeed [return a Promise for `publish()`](https://github.com/benbria/node-amqp-connection-manager#channelwrapperpublish-and-channelwrappersendtoqueue), which will behave like you probably expect it to.

**Comment by jcready** [comment]
@jwalton as we discussed two years ago (man time flies) the purpose of returning a boolean is so that you have some way to know that you are getting back pressure. Without that knowledge you may end up running out of memory when you're publishing messages faster than the network can actually send them. So there is a legitimate reason for this library to provide that information.

**Comment by jwalton** [comment]
Yup, I remember that discussion, and remember wondering if I'd made a terrible mistake in amqp-connection-manager by flipping it.  :P  I'm not sure if I ever came to a conclusion or not though.

**Comment by cressie176** [comment]
Confusion around ch.publish not returning a promise comes up quite a lot. Another common problem is the "Channel ended, no reply will be forthcoming" one. I think we should leave the API as is, but add a "Troubleshooting" section to the README, so hopefully save users some pain and reduce the noise.

**Comment by cressie176** [comment]
I've added a [troubleshooting](https://amqp-node.github.io/amqplib/#troubleshooting) section to the main documentation and referenced it from the readme.
