### ISSUE TITLE
Blocking channel.get?

### ISSUE THREAD

**Issue by ristkof** [amqp-node/amqplib#189]
It is my understanding that channel.get calls are non-blocking. Is this correct?

Running this script runs until user presses ctrl-c, which I would not have expected:

```
#!/usr/bin/iojs

var amqp = require('amqplib/callback_api');

amqp.connect('amqp://localhost', function(err, conn) {
  conn.createChannel(function(err, ch) {
    var q = 'discoverq';

    ch.assertQueue(q, {durable: false});
    console.log(" [*] Waiting for messages in %s. To exit press CTRL+C", q);
    var objectGot = ch.get(q,{noAck: false},function(err,msgOrFalse)
        {
                console.log(msgOrFalse.content.toString());
                ch.close();
        });
  });
});
```

What am I doing wrong? (this is probably a newby question). Thanks!

**Comment by squaremo** [comment]
Closing the channel leaves the connection open, and Node.JS won't exit until there's nothing waiting for I/O. So if you want to exit as soon as you get something from the queue, you should also close the connection in that callback. Make sense?

Incidentally, if you set `{noAck:false}`, you're saying you intend to acknowledge each message, so you ought to call `ch.ack(msgOrFalse);` before closing the channel (unless you want the message to go back on the queue).

**Comment by kristofvanlandschoot** [comment]
Perfect, thanks!

**Comment by kristofvanlandschoot** [comment]
Related issue: if I ack the message and then immediately close the connection the ack doesn't get to the server, so the message remains in the queue.

So: 
        ch.ack(msgOrFalse);
        ch.close();
        conn.close();

will give me the same message over and over again. Do I need to check if the connection is still busy before closing it? There does not seem to be a callback for when ack is finished?

**Comment by cressie176** [comment]
Looks like you may have forgotten to await on both the channel and connection close events
