### ISSUE TITLE
Order of operations on error/close with connections/channels

### ISSUE THREAD

**Issue by myndzi** [amqp-node/amqplib#20]
The docs say that channels implicitly emit close events when a connection closes, but I can't see any code in channel_model.js or channel.js that does this (I assume it's precipitated lower down?)

Either way, say you have a connection with two channels. Is there a defined order that the events will trigger in? If it errors, will I receive three close events and three error events? If it closes, will I receive three close events?

Will the connection emit its event first, or the channels?

Is there a way to tell in the channel close/error event if it was caused by the connection closing? Is there a property to determine the current state of a connection/channel in general?

Sorry if any of these are answered in the docs, I did look first.

**Comment by cressie176** [comment]
Closing due to age
