### ISSUE TITLE
Name connection

### ISSUE THREAD

**Issue by pablote** [amqp-node/amqplib#217]
is it possible to change the connection/client name that shows up on rabbitmq management interface?

**Comment by michaelklishin** [comment]
No.

**Comment by michaelklishin** [comment]
Relevant: https://github.com/rabbitmq/rabbitmq-server/issues/104.

**Comment by pablote** [comment]
rabbitmq already shows a client column on the connections tab which currently says "amqplib ..", I was hoping to be able to override that value

**Comment by michaelklishin** [comment]
@pablote see the issue above.

**Comment by squaremo** [comment]
Hi @pablote 

Yes, I think the fields in client properties are arbitrary, and RabbitMQ will just show whatever it gets; so we could add a "friendlyName" property in there. You'll only see if if you click through to see each connection (unless and until RabbitMQ add a friendly name facility), but you'll at least be able to distinguish the connections.

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-server/issues/104 will be included into `3.6.2`. To set a (human-readable) connection name that will be displayed in the management UI, include `connection_name` into client properties.

**Comment by cdynak** [comment]
Ok, things like this works as expected:
```
const amqp = require('amqplib');
amqp.connect('amqp://localhost', {clientProperties: {connection_name: "myFriendlyName"}});
```
So why this issue is still open?
Maybe this option could be mentioned somewhere in documentation?

**Comment by tarzansarka** [comment]
Is it possible to access this value on a connection instance?

**Comment by cressie176** [comment]
Updated

**Comment by shwarcu** [comment]
Hi, it doesn't seem to work anymore, I am using RabbitMQ 3.13.6 and `?` is displayed instead of connection name, under IP address
