### ISSUE TITLE
Document Public/Private API

### ISSUE THREAD

**Issue by skeggse** [amqp-node/amqplib#23]
It would be nice, for reference, if the code itself contained more documentation. The comments are excellent, but more organization and a clearer specification of whether a method/function is public or private would be nice.

Consider using JavaDoc/JSDoc syntax:

``` js
/**
 * Construct a new Connection object.
 *
 * @param {Stream} underlying The stream the Connection should bind to.
 * @constructor
 */
function Connection(underlying) {
  ...
}

/**
 * Close with a reason and a 'code'. I'm pretty sure RabbitMQ totally ignores
 * these; maybe it logs them. Returns a promise that will be resolved when the
 * CloseOk has been received; NB the 'close' event will be emitted once the
 * underlying stream is ended.
 *
 * @param {string} reason
 * @param {number}
 * @public
 */
C.closeBecause = function(reason, code) {
  ...
};

/**
 * A close has been initiated. Repeat: a close has been initiated. This means we
 * should not send more frames, anyway they will be ignored. We also have to
 * shut down all the channels.
 *
 * @private
 */
C.stop = function() {
  ...
};
```

**Comment by soryy708** [comment]
New JS feature: Private class features
> private class members can be created by using a hash # prefix. The privacy encapsulation of these class features is enforced by JavaScript itself.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

**Comment by cressie176** [comment]
Hi @soryy708,
Thanks for the suggestion, however [amqplib supports node 10 and above](https://github.com/amqp-node/amqplib/blob/main/package.json#L12), meaning we are not able to introduce some of the more recent JavaScript features.
