### ISSUE TITLE
unclear from docs what Channel#checkExchange return

### ISSUE THREAD

**Issue by srkimir** [amqp-node/amqplib#232]
Spent two hours trying to understand why `channel.checkExchange('Something')` returns `{}` even when exchange exists (check via `http://localhost:15672/#/exchanges`). On first, it seems like `{}` means that exchange does not exists, but then i saw on api docs:

> Check that an exchange exists. If it doesn't exist, the channel will be closed with an error. If it does exist, happy days. 

It can be misleading, it is not clear what `{}` means when there is no error and channel remain open, i can guess it means that there is exchange by given name?

**Comment by cressie176** [comment]
Agree it's a bit odd, however it is [documented](https://amqp-node.github.io/amqplib/channel_api.html#channel_checkExchange)
