### ISSUE TITLE
RabbitMQ Connection 'Error: Can't set headers after they are sent.'

### ISSUE THREAD

**Issue by ganeshkaila** [amqp-node/amqplib#241]
I can see `Error: Can't set headers after they are sent.` at RabbitMQ Connection `error` events.  In my coding, I am trying to invoke `confirmChannel.publish('exchange_name', routingKey, data, function () {...});` along with redis-limiter module code. The sample code snippet would be look like this

I already created RabbitMQ Connection and confirmChannel. And, using only `confirmChannel.publish();` to send messages.

```
var redis = require('redis');
var client = redis.createClient();
var RedisLimiter = require('redis-limiter');
var limiter = new RedisLimiter({
   client: client,
   prefix: 'lim'
});

// 2 requests per second
limiter.add('/api/action', {
   limit: 2,
   interval: 1
});

app.get('/api/*', function(req, res, next) {
   limiter.limit(req.path, req.ip, function(err, result) {
      if (err || !result) {
         return next();
      }

      if (result.exceeded) {
         return res.sendStatus(429);
      }
      next();

     // had confirmChannel object
     confirmChannel.publish('exchange_name', routingKey, new Buffer(data), {
             persistent: true,
             mandatory: true
      }, function (err, ok) {
        if(err) console.error('Not delivered');
        else console.log('Message delivery success.');
     });
   });
});
```

And, i trying to send request from `siege` load test. 

`siege -c10 -t1M http://localhost:port/api/action`

**Comment by squaremo** [comment]
> I can see Error: Can't set headers after they are sent.

Hmm, I don't think that's an error that RabbitMQ or amqplib reports; perhaps it's provoked by setting a status code on the `res`ponse?

**Comment by gkved** [comment]
But, this `error` coming from RabbitMQ Connection. I am very sure, look this snippet 

    conn.on('error', function(err) {
      console.error('RabbitMQ Connection ' + err);      
    })

On my console, it prints as 

    RabbitMQ Connection Error: Can't set headers after they are sent.

Even if the `error` belongs to status code on response as you said. 
Will those error events come under `amqp.conn.on('error', function(){...});`?

**Comment by cressie176** [comment]
This is most probably happening because you are getting a connection error after your application has sent the HTTP response headers. It's a common when you call next() within middleware without returning.

I suspect something is catching the connection error then trying to set the status code to 500, but because the headers have already been sent this results in the "Can't set headers after they are sent" message.
