### ISSUE TITLE
read ECONNRESET

### ISSUE THREAD

**Issue by auror** [amqp-node/amqplib#245]
Frequently getting the "**read ECONNRESET**" errors in error callback. Look at my code snippet

```
function connect(callback) {
     console.log("AMQP: Trying to connect");
     amqp.connect("amqp://username:password@ip:5672/%2F?heartbeat=5", function(err, connection) {
        console.log("AMQP: Got a call from amqplib")

        function retry(){
            setTimeout(function(){
                connect(callback);
            }, 5000);
        }

        if(err){
            retry();
        }
        else{
            me._connection = connection;

            connection.on('close', function(){
                me._connection = null;
                retry();
            });

            connection.on('error', function(err){
                me.connected = false;
            });

            callback.call();
        }
    });
};
```

Whenever i get this error, 'close' callback was also called. So, i retry the connection after 5 seconds, but the supplied callback in amqp.connect was never called as i don't see the log **"AMQP: Got a call from amqplib"**

Meanwhile RabbitMQ logs say "**closing AMQP connection. Missed heartbeats from client, timeout: 5s**"

When do i get Connection reset error? and Why am i not able to create a new connection while reconnecting?

Also, the no: of connections made to RabbitMQ by that process started increasing from 1 to many(Reference: netstat)

**Comment by auror** [comment]
@squaremo Did u get time to look into this problem?

**Comment by cressie176** [comment]
The code snippet works for me. It's been a long time so maybe something changed in amqplib.
