### ISSUE TITLE
listening for disconnect event, is it possible?

### ISSUE THREAD

**Issue by srkimir** [amqp-node/amqplib#246]
Is it possible to register a handler for something like `disconnect` event? This would be good to have,  especially in cases when RabbitMQ server unexpectedly goes down? Looking through documentation and source code i didnt find anything like that

**Comment by squaremo** [comment]
http://www.squaremobius.net/amqp.node/channel_api.html#model_events has the events for a connection, including `close` and `error`. (Now that I look, it's not very clear that the `Model` prototypes correspond to connections -- they are an implementation detail. I ought to rename them.)

**Comment by srkimir** [comment]
@squaremo thank you for response, +1 for renaming
