### ISSUE TITLE
Start a mailing list for support/questions

### ISSUE THREAD

**Issue by michaelklishin** [amqp-node/amqplib#249]
Most issues in this repository are questions. Please consider starting a mailing list and directing all support questions there, and close them here.

Having issues-that-are-questions makes it harder to notice legitimate issues for both users and potential contributors. GitHub issues are hardly a great medium for user support from my experience.

**Comment by japel** [comment]
besides that, a gitter.im channel would be awesome!

**Comment by cressie176** [comment]
After reading some of the questions I sympathise - there's a lot of people asking who haven't read the channel api or basic amqp concepts docs.

Having said that I've never had much luck with mailing lists. Multiple places to post questions causes confusion, and generates resentment when asked to re-post elsewhere. I really like the conversational aspects of github issues, and GitHub flavoured markdown is great for showing example code.

Maybe i've not found the "right" way (or timezone) to ask questions but IM always seem to end up with a bunch of people, squatting in a room saying nothing.

As an alternative tagging issues as "question", "investigate", "feature request" and "bug" can help make it more obvious which ones are worth addressing.

Another option is [issue templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

Just my 2c

**Comment by cressie176** [comment]
Whatever the decision I'd suggest an issue sweep up. Several issues (e.g. https://github.com/squaremo/amqp.node/issues/202 and https://github.com/squaremo/amqp.node/issues/215) are so old I doubt they're relevant. I'd be happy to help.

**Comment by michaelklishin** [comment]
@cressie176 👍

**Comment by michaelklishin** [comment]
@cressie176 thank you for your help with this library 👏
