### ISSUE TITLE
How to determine all message is sent so I can close the connection without worry?

### ISSUE THREAD

**Issue by Jianru-Lin** [amqp-node/amqplib#254]
My application will invoke the `channel.sendToQueue()` many times, and then it will invoke `connection.close()` immediately. The problem is I'm not sure will it drop the data that not be sent yet or not? If it is, how should I handle this issue?

Thanks very much.

**Comment by HERRKIN** [comment]
I have the same issue, I don't know if a message got send so I can save it to the db, if the connection closes there is no way to know if rabbit got the message so I can save that the message was sent.

**Comment by squaremo** [comment]
@Jianru-Lin @HERRKIN Confirmations are exactly for this purpose. In RabbitMQ (background): http://www.rabbitmq.com/confirms.html and in amqplib: http://squaremo.github.com/amqp.node/channel_api.html#confirmchannel

**Comment by HERRKIN** [comment]
ok but is there a way to do it like this 
`channel.publish(args).then(handle, error)`
or something similar? I tried `rabbit.ch.waitForConfirms( )`  but it wont throw error, I have to wrap the publish call in try/catch in order to handle it, I think it is not so effective, I am used to work with promises, its easier to do `channel.publish(args).then(ok,errorHantler) `don't you think?

**Comment by squaremo** [comment]
The return value of `publish` is used for flow control (like streams). You could certainly wrap `publish` in a function that returns a promise, if you're willing to ignore flow control. (And if you're synchronising on every message, that is surely safe to do)

**Comment by HERRKIN** [comment]
I am a little confused, can you give me an example?

**Comment by jcready** [comment]
Publish returns a boolean indicating whether or not the message was successfully written or buffered into memory. If it returned false then you should wait for the drain event before continuing to publish messages to the queue otherwise you risk running out of memory.

**Comment by igrcic** [comment]
Hi everyone,

i'm also having trouble figuring this one out. 
Using promises, sendToQueue doesnt return any return value as publish is, as suggested.

Doing the following;:
```
channel.waitForConfirms().then((result) => { 
    channel.close();
})
```
yields in 
```
Potentially unhandled rejection [111] Error: Channel ended, no reply will be forthcoming
    at rej (node_modules\amqplib\lib\channel.js:190:7)
    at ConfirmChannel.C._rejectPending (node_modules\amqplib\lib\channel.js:196:42)
    at ConfirmChannel.C.toClosed (node_modules\amqplib\lib\channel.js:160:8)
    at ConfirmChannel.C.toClosing.k.accept (node_modules\amqplib\lib\channel.js:179:12)
    at Connection.mainAccept [as accept] (node_modules\amqplib\lib\connection.js:63:33)
    at Socket.go (node_modules\amqplib\lib\connection.js:476:48)
```
I see that result value is an array of undefined values (length equals to sendToQueue calls number). Im not sure what should I do with that.

Is there a way to close the channel after all the messages have been published using sendToQueue?
I see that the example `examples/waitForConfirms.js` closes the connection, not the channel.

Is that the preferred way?

Thank you,
Ivan

**Comment by cressie176** [comment]
The following should work...

```js
const amqp = require('amqplib');

(async () => {

  const connection = await amqp.connect({
    host: 'localhost',
    port: 5672,
  })

  const regularChannel = await connection.createChannel();
  await regularChannel.assertQueue('test');
  await regularChannel.close();

  const confirmChannel = await connection.createConfirmChannel();
  for (let i = 0; i < 100000; i++) {
    confirmChannel.sendToQueue('test', Buffer.from('foo'));
  }

  await confirmChannel.waitForConfirms();

  await confirmChannel.close();
  await connection.close();
})();
```
