### ISSUE TITLE
How can I prevent channel close if a queue does not exist when I us checkQueue?

### ISSUE THREAD

**Issue by cage1618** [amqp-node/amqplib#280]
How can I prevent channel close if a queue does not exist when I us checkQueue?

I don't want to close the channel. Thanks a lot!

**Comment by khannavidur** [comment]
As per http://www.squaremobius.net/amqp.node/channel_api.html#channel_checkQueue , checkQueue function will bork the channel if the named queue doesn't exist

But something like this worked for me.

```
rmq.prototype._getQCount    = function(cb, qName){
    var self = this;

    self.channel.checkQueue(qName)
        .then(function(qResp) {
            return cb(qResp.messageCount);   
        },function(error){
           console.log("queue error - ",error);
           return cb(-1);
        });
};
```

Here I am getting the message count in a queue.  Even if the queue does not exist, the channel won't be borked.

**Comment by squaremo** [comment]
The behaviour of `checkQueue` is dictated by the protocol, but it can be worked around. One tactic is to create a "sacrificial" extra channel with which to test whether the queue exists. Once you have the answer, you can throw the extra channel away, or keep it around for more tests.

**Comment by vasinsky** [comment]
ты чё несёшь ? )) как проверить наличие?
