### ISSUE TITLE
Graceful closing of channels

### ISSUE THREAD

**Issue by LinusU** [amqp-node/amqplib#285]
How would you feel about a someway to gracefully closing a channel, that is letting all current actions on it be done, and then closing it.

Something like:

``` js
channel.sendToQueue('test', new Buffer('hello'))
channel.sendToQueue('test', new Buffer('hello'))
channel.sendToQueue('test', new Buffer('hello'))
channel.close(true).then(() => console.log('done'))
```

When "done" is logged all the messages should have been sent and confirmed to the queue.

The way I'm imaging it being implemented would be to track all outgoing requests that expects answers, and when doing the close waiting for that number to go down to zero before doing the close. It would also be nice to throw an error if you try to do anything more on the channel after `.close(true)` has been called...

**Comment by michaelklishin** [comment]
There is a protocol method that does just that: `channel.close`. All popular clients implement it.

**Comment by FarzanRNobakht** [comment]
same problem with:
`connection.close()`
it does not wait for sent messages to be delivered completly and So closing connection Cancells them:
`this.ch.sendToQueue(conf.queueName, new Buffer(JSON.stringify("hi!")));
                    conn.close();`

**Comment by cressie176** [comment]
Have you tried using a confirm channel and closing the channel / connection in the callback? See [the channel api](http://www.squaremobius.net/amqp.node/channel_api.html) docs.

**Comment by klesun** [comment]
@cressie176 using `createConfirmChannel()` instead of `createChannel()` does not seem to make any difference, `conn.close()` still discards messages passed to `sendToQueue()` if I don't put a short sleep before closing.
