### ISSUE TITLE
[PATCH] channel acceptDeliveryOrReturn() can cause channel error if queue has waiting messages

### ISSUE THREAD

**Issue by rgagnon24** [amqp-node/amqplib#290]
If a queue has published messages in it that a subscriber has not consumed, AND prefetch is set to a value smaller than the number of messages in the queue, the channel will immediately close with error when `.consume()` is invoked.

Let's assume 10 or more messages are in queue when the consumer of the queue finally starts running, and prefetch on the channel is set to 1.

The reason for the error this is that the `.handleMessage` property of `Channel` does not have time to reset to `acceptDeliveryOrReturn` after the `content()` method has completed all content for a message.

When `content()` method decides that all content frames have been consumed, it calls `continuation(message)` and the value of `.handleMessage` is still pointing to content.

The event "delivery" is raised, but the `content()` method is called again with the next frame before `.handleMessage` gets a chance to be reset to be `acceptDeliveryOrReturn`.

This causes the BasicProperties frame of the next message to be sent to `content()`, which throws "Expected content frame after headers"

The solution I found is to defer the emitting of the event until the next turn around the event loop by changing the method's contents as in this tiny diff:

``` javascript
--- channel.js.before   2016-10-04 21:59:10.418599788 +0000
+++ channel.js  2016-10-04 21:58:05.000000000 +0000
@@ -260,7 +260,9 @@
   var fields = f.fields;
   return acceptMessage(function(message) {
         message.fields = fields;
-        self.emit(event, message);
+        process.nextTick(function() {
+               self.emit(event, message);
+        });
   });
 }
```

This allows time for the `.handleMessage` property to properly reset to the return value from `content()`

**Comment by krishnasrk** [comment]
I also hit the same issue and the suggested patch, solved the issue.

**Comment by cressie176** [comment]
I've been unable to reproduce...

I loaded a queue with a few thousand messages then ran the following repeatedly.

```js
const amqp = require('amqplib');

(async () => {
  const connection = await amqp.connect();
  const channel = await connection.createChannel();
  await channel.assertQueue('test');

  channel.prefetch(1);
  let i = 0;
  let { consumerTag } = await channel.consume('test', async (message) => {
    i++;
    console.log(i, message.content.toString());
    channel.ack(message);
    if (i === 10) {
      await channel.cancel(consumerTag);
      setTimeout(async () => {
        await channel.close();
        process.exit();
      }, 2000)
    }
  }, { noAck: false });

})()
```

Going to close as the issue is so old, but if anyone experiences this again please re-raise.
