### ISSUE TITLE
Missleading in doc on .ack, .nack methods. Methods do not return promise and do not have callback

### ISSUE THREAD

**Issue by kyptov** [amqp-node/amqplib#294]
In the [doc](http://www.squaremobius.net/amqp.node/channel_api.html#channel_ack) there is ambiguity. 
Line:

> **Promises and callbacks**

missleading, actually this methods returns nothing and don`t have callbacks.

**Comment by squaremo** [comment]
You are right -- what I mean by "Promises and callbacks" is that the docs apply to both the promise- and callback-flavoured APIs, but it's ambiguous isn't it. I should think of a better way to state it (maybe just by having separate docs for each flavour).

**Comment by cressie176** [comment]
I've added notes to the documentation for methods that do not return a promise or accept a callback
