### ISSUE TITLE
Expose constants from lib/defs

### ISSUE THREAD

**Issue by jsrraman** [amqp-node/amqplib#310]
Please expose the constants defined in lib/defs to the outside world.

**Comment by gigouni** [comment]
Still nothing ...

up

**Comment by michaelklishin** [comment]
@jsrraman may I ask you what constants you need specifically and when/why? I'm not against the idea but exposing everything isn't necessarily a great idea.

**Comment by cressie176** [comment]
Closing due to lack of response
