### ISSUE TITLE
Is there a way to give multiple hosts in the connection parameters. 

### ISSUE THREAD

**Issue by prajapatkiran** [amqp-node/amqplib#319]
My client is connected to a rabbitmq cluster. It should be able to failover to the next node in the cluster.  Can I give multiple hosts in connection params? If not, it would be nice to support the address array support similar to how the Java client does.

**Comment by thebigredgeek** [comment]
@squaremo any update on this?

**Comment by cressie176** [comment]
I don't think this is supported with amqplib but it's easy to implement by looping through a randomised array of hosts until you find one that works. See [here](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/tasks/createConnection.js#L12-L25) for an example.

**Comment by galaxyfeeder** [comment]
It would be very nice to have this implemented onto this library.

**Comment by roysG** [comment]
Yes 👍

**Comment by SacDin** [comment]
https://github.com/guidesmiths/rascal supports this
