### ISSUE TITLE
Unable to resolve Promise - Consume from a queue

### ISSUE THREAD

**Issue by anishnair02** [amqp-node/amqplib#324]
I have read the documentation for Promise and it says that Promise can only be resolved once.

Consider the scenario.
I want to receive messages and send it back to a worker(who will decide what to do with the messages)

I have a generic amqp connector.js file and a worker.js

Here's the receiving part for connector.js
```
var receiveMessage = function(ch, queueName) {
    return recvMsgPromise = new Promise(
        function(resolve, reject) {
            var q = queueName;
            ch.consume(q, function(msg) {
                if(msg) {
                    console.log('Received message', msg);
                    resolve(msg);
                } else {
                    console.log('Message is not defined');
                    msg = 'Could not send message to queue'; // Setting error msg..
                    reject(msg);
                }
            });
    });
}
```

Here's the worker - who gets the job from the queue (this will call the connectors receiveMessage() once when it starts)
```
var receiveJobs = function() {
    console.log('receiveJobs');
    connector.receiveMessage(receiverCh, 'emailQueue') // Calling function from connector - above function..
    .then(
        function(res) {
            console.log('Error receiving message', reason);
        })
    .catch(
        function(reason) {
            console.log('Error receiving message', reason);
        });
}
```

This works the first time a job is added to the queue.
But not able to get the 2nd job (I add a new job in runtime - where both the apps are running independently)
This is because the connector.js Promise is already resolved once.

When I was using the callback method earlier, this did not create a issue, and callbacks will never.
But with Promises it does.

After the ch.consume in connector.js, callbacks would return it back to the place where it was called from(i.e in the worker.js receiveMessage()). But with promise it resolves it only once and so not returning back to the worker.js

**Comment by kleicht** [comment]
You need to acknowledge the message to the channel once the job is done. By default, the server waits for the first message acknowledgment before sending the second message and so on.

**Comment by anishnair02** [comment]
Hi @kleicht 
I understand that the job needs to be acknowledged. But I think you misunderstood my ticket/issue.

The problem is, after new jobs are added to the queue, the connector.js doesn't send the job back to the worker.js(because the relation between both was resolved once using Promise. and a Promise can only be resolved once. But the same is not the case with callbacks. With callbacks, you can always send it back to the worker.js)

Hope I am clear now.

**Comment by squaremo** [comment]
The way you've structured the code above, `receiveMessage` is called once, so only one promise is constructed, so only one promise is available to be resolved.

If you're decided on using promises to represent incoming messages, what you'll have to do is call `receiveMessage` more than once -- in fact, call it until there are no more messages. To do that, you'll need to move the call to `consume` outside it (you only want to do that once), and call `receiveMessage` from the success continuation (`function(res) { ...}`).

**Comment by squaremo** [comment]
Hi @anishnair02, did you have another look at this?
