### ISSUE TITLE
Involuntarily deleted Queue 

### ISSUE THREAD

**Issue by serhatates** [amqp-node/amqplib#335]
Hi,
Let's say somehow  queue is deleted.  Is there anyway to recreate queue automatically and running properly without restart the app? 

Thanks in advance

**Comment by michaelklishin** [comment]
Applications declare queues, optionally verifying if they exist with a passive declare (which results in a channel error if the queue does not exist). There is no other way.

**Comment by serhatates** [comment]
Even if i decleare queue manually and bind to its exchange doesn t send messages to queue can we do some recovery without restart the app? Can we do  remedy code in the comment ?
```JavaScript
// Message consumer
function consumer(conn) {
    var ok = conn.createChannel(on_open);
    function on_open(err, ch) {
        if (err != null) bail(err);
        ch.assertExchange(exchange, 'x-delayed-message', { durable: true, arguments: { 'x-delayed-type': 'direct' } });
        ch.assertQueue(queue, { durable: true });
        ch.checkQueue(queue, function (err, ok) {
            if (null !== err) {
                // Can some remedy code here with ?              
            }
        });
        ch.bindQueue(queue, exchange, queueBinding);
        ch.consume(queue, function (msg) {
            if (msg !== null) {
                console.log(msg.content.toString());
                ch.ack(msg);
            }
        });
    }
}
```

**Comment by michaelklishin** [comment]
What do you mean by recovery?

You can do whatever you want in a callback but if there was an error, the channel will be closed so you have to open another one. This is where using only callbacks becomes really tricky and requires refactoring of a switch to futures (promises).

**Comment by serhatates** [comment]
I mean how i can open a channel without restart the app? If i add queue manually, exchange can send messages to queue but consumer could not consume message because of borked channel.

**Comment by serhatates** [comment]
You mean something like that ? 
```JavaScript
amqp
    .connect('amqp://bsp:bsp123@2.12.110.12:5672')
    .then(conn => conn.createChannel())
    .then(ch => {
        ch.assertExchange(exchange, 'x-delayed-message', { durable: true, arguments: { 'x-delayed-type': 'direct' } });
        return ch
            .assertQueue(queue, { durable: true })
            .then(() => ch.bindQueue(queue, exchange, queueBinding))
            .then(() => {
                ch.consume(queue, (msg) => {
                    // Handle delayed message
                    console.log(msg.content.toString('utf8'));
                    // ...
                }, { noAck: true });
            })
            .then(() => ch.checkQueue(queue));
    });

//ch.on('error', function () {...})  // Recreate queue and bind to exchange and open another channel
```

**Comment by serhatates** [comment]
I intentionaly delete queue from management UI, this error  occured and i couldn t catch it. 

![deletedqueue](https://cloud.githubusercontent.com/assets/12493738/23752871/c20dfcd4-04df-11e7-8c58-5174fbd6a5e3.jpg)

**Comment by cressie176** [comment]
Got caught by this myself. From the amqplib docs...

> If the [consumer is cancelled](http://www.rabbitmq.com/consumer-cancel.html) by RabbitMQ, the message callback will be invoked with null.

So you always need to test ```msg``` before accessing it's properties.
