### ISSUE TITLE
How to forcefully flush the publish stream

### ISSUE THREAD

**Issue by marvel308** [amqp-node/amqplib#342]
We have a node server which continuously publishes messages, in some cases when an error is thrown and the process restarts, the messages still in the stream are lost, is there any way to flush the stream before the app closes ?

**Comment by cressie176** [comment]
I don't think amqplib is buffering messages, it's probably that the error is encountered while multiple messages are inflight. Options are...

1. You can wait for the confirm before publishing the next message. This way you will only lose the current message, but performance will be reduced. A variation on this is to limit the number of unconfirmed messages and apply back pressure to the source (you sometimes need to do this when your source is streams data faster than you can publish it)

1. If the messages you are publishing originally came from a persistent store and the downstream systems support duplicates you can check off confirmed messages, and automatically retry un checked ones when your app restarts.

1. You can intercept the events that can kill your process, and wait for all messages to be confirmed, then gracefully shutdown your app, allowing it to be restarted.<br/><br/>You can use [outstanding](https://www.npmjs.com/package/outstanding) to keep track of your outstanding messages, and use / copy the code from [systemic-service-runner](https://github.com/guidesmiths/systemic-service-runner/blob/master/index.js) and [systemic-domain-runner](https://github.com/guidesmiths/systemic-domain-runner/blob/master/index.js) to listen for *killer* events. The last two links make more sense if you familiarise yourself with [service-example](https://github.com/guidesmiths/svc-example).<br/><br/>However the above approach will fail if the error killed the channel or connection, or if someone or something issues a SIGKILL.

**Comment by marvel308** [comment]
After the message is sent the app is shutting down gracefully
`var cluster = require('cluster');
var workers = parseInt(process.env.CLUSTER_WORKERS, 10) || 1;
var promise =  require('bluebird');
var ErrorLoggingService = require('./../classes/Service/LoggingService/JsonErrorLoggingService');
var StaticFunctions = require('./../classes/Utilities/StaticFunctions');
var staticFunctions = new StaticFunctions();
var errorLoggingService = new ErrorLoggingService(new StaticFunctions());

process.on('unhandledRejection', function(reason, p){
    console.log("Possibly Unhandled Rejection on Date " + staticFunctions.getLogDate() + " at: Promise " + p + " reason: " + reason);
    throw new Error(reason);
    // application specific logging here
});

promise.onPossiblyUnhandledRejection(function(reason, p){
    console.log("Promise onPossiblyUnhandledRejection on Date " + staticFunctions.getLogDate() + " at: Promise " + p + " reason: " + reason);
    if(reason.name !== "OperationalError" && reason.message !== "Redis connection to undefined failed - write EPIPE")
        throw new Error(reason);
});

promise.onUnhandledRejectionHandled(function(promise){
    console.log("Promise onUnhandledRejectionHandled for " + promise);
});

if(cluster.isMaster){

    process.on('uncaughtException', function(err) {
        console.log('Caught exception:  on Date ' + staticFunctions.getLogDate() + " Error : "  + err);
        var errMsg = err + " " + err ? err.stack : "";
        errorLoggingService.logAndMailErrorSafely("error", errMsg)
            .then(function(){
                process.exit(1);
            });
    });

    cluster.mappingTable = {};
    for (var i = 0; i < workers; i++) {
        var worker = cluster.fork({'workerId' : i});
        worker.on('message', function(msg) {
            cluster.mappingTable[msg.pid] = msg.workerId;
        });
    }
    cluster.on('listening',function(worker,address){
        console.log('worker      => start with pid: ' + worker.process.pid);
    });
    cluster.on('exit', function(worker, code, signal) {
        console.log('worker      => with pid: '+ worker.process.pid+' ,died. Restarting... ');
        var id = cluster.mappingTable[worker.process.pid];
        delete cluster.mappingTable[worker.process.pid];
        setTimeout(function() {
           var worker = cluster.fork({'workerId' : id});
           worker.on('message', function(msg) {
               cluster.mappingTable[msg.pid] = msg.workerId;
           });
        },2000);
    });
}
else{

//    var debugPort = 5858 + cluster.worker.id;
//    console.log(debugPort);
//    process._debugPort = debugPort;

    var debug = require('debug')('src');
    var app = require('../app');
    app.set('port', process.env.PORT || 3000);
    var server = app.listen(app.get('port'), function() {
        debug('Express server listening on port ' + server.address().port);
    });

    var max = 150;
    var min = 300;
    setProcessRequestNumberOut(server, Math.floor(Math.random() * (max - min + 1)) + min);

    process.send({pid: process.pid, workerId: process.env.workerId});

    process.on('uncaughtException', function(err) {
        var errMsg = err + " " + (err ? err.stack : "");
        console.log('Caught exception error : ' + errMsg);
        errorLoggingService.logAndMailErrorSafely("error", errMsg)
            .then(function(){
                //process.exit(1);
                var killtimer = setTimeout(function() {
                    console.log("Exiting process")
                    process.exit(1);
                }, 30000);

                console.log("Closing server");
                // stop taking new requests.
                server.close(function() {
                    console.log("Closed out remaining connections.");
                    app.emit('close');
                });

                app.on('rabbitMqClosed', function () {
                    process.exit(1);
                });

                // But don't keep the process open just for that!
                killtimer.unref();
            });
    });



}`

whenever an exception is caught rabbitMQ is closed and the app emits a "rabbitMqClosed" event which leads to process.exit(1), somehow still the messages are lost

**Comment by cressie176** [comment]
- Are you using a confirm channel when you publish messages?
- Are you waiting for all confirmations to return before emitting rabbitMqClosed?
- Are you ceasing to publish messages as the first step of the shutdown process?

**Comment by marvel308** [comment]
Yes, we are ceasing to publish messages as the first step of exit process, We can't do the 1st and 2nd step as it would increase our response time

**Comment by cressie176** [comment]
That sounds very much like your problem then. If you're exiting the application but not confirming messages have been published, when you kill the application inflight messages are going to be lost. I understand you have a concern about performance of confirm channels. What about the following...

1. Receive data
2. Increment inflight & total counter
3. Publish message to a confirm channel
4. Repeat

In parallel

1. Receive confirmation
2. Increment confirmed counter

On shutdown request

1. Block incoming data
2. Wait for Inflight === 0 and confirmed === total
3. Shutdown

This way you can still publish messages concurrently.

**Comment by marvel308** [comment]
I was curious about the streams which are in https://github.com/squaremo/amqp.node/blob/master/lib/mux.js , I was wondering if I could forcefully publish all messages in the stream before exiting

**Comment by squaremo** [comment]
> I was curious about the streams which are in https://github.com/squaremo/amqp.node/blob/master/lib/mux.js , I was wondering if I could forcefully publish all messages in the stream before exiting

In principle, every frame waiting to be written could be flushed to socket in a single loop. But it wouldn't really help you, since they could write to Node's own overspill buffer, which gets thrown away when exiting.

If you want to make sure everything has reached the server before shutting down, you can send an RPC on each channel (e.g., `channel.close()`). Once those have been resolved, you know the server has seen every frame you sent beforehand.
