### ISSUE TITLE
heartbeat=0 connection option is ignored

### ISSUE THREAD

**Issue by UnbounDev** [amqp-node/amqplib#344]
Using `"amqplib": "^0.5.1"`

Repro by setting `heartbeat=0` and log internal `connection.heartbeat` value:
```
let open = amqp.connect("amqp://guest:guest@127.0.0.1:5672?heartbeat=0");
open.then((conn) => {
      return conn.createChannel();
    }).then((ch) => {
      console.log("amqp hb", ch.connection.heartbeat);
      // => amqp hb 60
});
```

Workaround by explicitly clearing the heartbeat after connecting:
```
...connect, then...
ch.connection.heartbeater.clear();
```

**Comment by squaremo** [comment]
RabbitMQ has a default of 60s (https://www.rabbitmq.com/heartbeats.html) and if you specify `0`, the server's value is used. More information on how this negotiation works is at https://github.com/squaremo/amqp.node/pull/83#issuecomment-50988301

NB the documentation text about vetoing or disabling the heartbeat is misleading -- if the server has a default, you can lower it, but you can't disable it.

**Comment by cressie176** [comment]
The RabbitMQ team have improved the heartbeat documentation to make this less confusing.
