### ISSUE TITLE
rejectUnauthorized : false has no effect

### ISSUE THREAD

**Issue by bluedge** [amqp-node/amqplib#352]
I'm connecting a bunch of slave servers to a master server (all in diff. countries) with amqp**s**
The master server has a certificate but the slaves server don't (they only have IP, no DNS)
I'm adding the rejectUnauthorized option to the SSL parameters but it doesn't seem to have any effect. Using NODE_TLS_REJECT_UNAUTHORIZED=0 is not an option I would favor.
`const ssl = {
	rejectUnauthorized : false,
	cert	: fs.readFileSync(config.getSSLOptions('cert')),
	key		: fs.readFileSync(config.getSSLOptions('key')),
	passphrase	: config.getSSLOptions('passphrase'),
	ca		: [fs.readFileSync(config.getSSLOptions('ca'))]
}`

**Comment by cressie176** [comment]
@bluedge it's been so long I'm going to close this (sorry). There's not enough debug to go on, and I doubt it was an amqplib since the `rejectUnauthorized` is honoured...

```javascript
// docker run -d --rm -p 5671:5671 -v $(pwd)/docker:/home/client rabbitmq-with-ssl:latest

const amqp = require('amqplib');
const fs = require('fs');
const cert = fs.readFileSync('./docker/cert.pem');
const key = fs.readFileSync('./docker/key.pem');

var opts = {
  rejectUnauthorized : false,
  cert,
  key,
  clientProperties: {
    connection_name: 'amqplib-352',
  }
};

(async () => {
  const connection = await amqp.connect('amqps://localhost', opts);

  const channel = await connection.createConfirmChannel();
  await channel.assertQueue('test', { durable: false, autoDelete: true })

  channel.sendToQueue('test', Buffer.from('amqplib-352'));
  await channel.waitForConfirms();

  const message = await channel.get('test');
  console.log(message.content.toString());
})();
```
If I comment out the rejectUnauthorized property I get the following
```
(node:7416) UnhandledPromiseRejectionWarning: Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by SSANSH** [comment]
+1
