### ISSUE TITLE
channel#ack() does not throw an error if called after channel has died

### ISSUE THREAD

**Issue by dotkas** [amqp-node/amqplib#353]
Hi @squaremo.

I am trying to implement an "at most once"-queue. Therefore it is really important that my software trusts an ACK only if the message has correctly been consumed. This should be pretty straightforward, but I have an example that seems to not be the case.

Taking the example from [the RabbitMQ tutorial](https://www.rabbitmq.com/tutorials/tutorial-two-javascript.html):

```
// Start by having a message pending in RabbitMQ, in the queue called 'queue'
const amqp = require('amqplib/callback_api');

amqp.connect('amqp://localhost', function (err, conn) {
    conn.createChannel(function (err, ch) {
        var q = 'queue';

        ch.assertQueue(q, {durable: true});
        ch.prefetch(1);
        console.log(" [*] Waiting for messages in %s. To exit press CTRL+C", q);
        ch.consume(q, function (msg) {
            var secs = msg.content.toString().split('.').length - 1;

            console.log(" [x] Received %s", msg.content.toString());
            setTimeout(function () {
                console.log(" [x] Done");
                ch.ack(msg); // Break execution here, stop RabbitMQ, continue execution
                console.log('This should not be called'); // This is called even RabbitMQ is down
            }, secs * 1000);
        }, {noAck: false});
    });
});
```

Is this working as intended? I was under the impression that `ch.ack(msg)` should crash with an exception, as `ch` should now be closed.

Thank you in advance.

**Comment by cressie176** [comment]
Hi @dotkas,

I'm surprised it doesn't crash, however I'm still not sure this would give you "at-most-once" messaging, since the message would have been delivered to your application once, then redelivered because it had not been acknowledged. For "at-least-once" messaging wouldn't you be better off with autoAck enabled (apologies if I'm missing something)?

**Comment by dotkas** [comment]
> (...) since the message would have been delivered to your application once, then redelivered because it had not been acknowledged.
Yes, you are quite right - this defeats the purpose of my "at most once" paradigm. But if the ack did crash as I was hoping it would, it would work as expected.

As for the autoAck, I cannot say. What is this exactly?

**Comment by cressie176** [comment]
Sorry my bad. I meant noAck, not autoAck. If you set noAck to true instead of false, the broker will dequeue the message without waiting for an ack, which is would give the "at-most-once" behaviour you were after

**Comment by dotkas** [comment]
That is true, but it would also defeat the purpose of actually using ack at all, which I would very much like to do. Maybe @squaremo has some input on why it does not throw exceptions.

**Comment by connec** [comment]
Sorry if I'm missing something, but why "ch should now be closed"? I don't see any `ch.close`s.

**Comment by michaelklishin** [comment]
@connec channels can be closed by the server when a channel-level exception happens. Double acknowledgements or acknowledgements of deliveries for a consumer using [automatic acknowledgement mode](http://www.rabbitmq.com/confirms.html) is one case that raises such exceptions.

**Comment by cressie176** [comment]
@dotkas looks like I'm still missing something here...

### At Most Once
```
ch.ack(msg)
doWork()
```

### At Least Once
```
doWork()
ch.ack(msg)
```

If you want At Most Once messages what difference does it make whether you explicitly ack the message or whether RabbitMQ dequeues automatically? i.e. what benefit does an explicit ack actually give you?

**Comment by dotkas** [comment]
@connec as @michaelklishin points out, I force-close the connection by ending the RabbitMQ instance while stopping my code execution. If you look at the line:

`                ch.ack(msg); // Break execution here, stop RabbitMQ, continue execution`
I am running this example through a debugging instance, where I stop the execution before `ch.ack(msg)`, then shut down the RabbitMQ instance, thus pretending a RabbitMQ crash scenario, where I would hope that any further execution will not happen due to an exception.

@cressie176 You are right, but my actual use case is a bit more complicated than the example. In my actual example, I am doing a lot of work before `ack`ing a message. So my use case is one where only dequeuing at the very last moment before "shipping off" the message would be preferable. In my mind this is sort of the normal use case for such a scenario.

**Comment by cressie176** [comment]
@dotkas I get the same thing when I run your example with node debugger, although I do get an error almost immediately afterwards. I suspect you need to bump any code after the ch.ack to the back of the event loop, using setImmediate or setTimeout(doWork, 0), the error will trip before your code runs

**Comment by connec** [comment]
My bad, I always confuse myself with `noAck: false`. Double negatives, how do they work? :sweat_smile:

**Comment by michaelklishin** [comment]
Some clients have switched to `manualAck` or similar (e.g. a union type for acknowledgement mode). This is a reasonable usability improvement to request for amqp.node ;)

**Comment by dotkas** [comment]
@cressie176 not completely sure how you mean, could you supply an example?

**Comment by cressie176** [comment]
For at most once, you need to ack before the executing the code you're trying to protect from duplicate messages, however as you found, ch.ack(msg) was appearing to work, even though you had stopped the broker, allowing the next line of code to execute. By wrapping in the sensitive code within a call to `setImmediate` it will be deferred, allowing the channel error to bubble up and crash your application (or be handled however you see fit)

```
ch.ack(msg)
setImmediate(() => {
  // do stuff
})
```
