### ISSUE TITLE
handshake_timeout on the server every time the client connects 

### ISSUE THREAD

**Issue by melalj** [amqp-node/amqplib#356]
I have been having this issue for a while and thought that it might comes from the amqp.node client instead of the server.

```
=INFO REPORT==== 30-May-2017::04:32:15 === 
accepting AMQP connection <0.32737.44> (10.0.1.128:34526 -> 10.0.2.174:5672)
=ERROR REPORT==== 30-May-2017::04:32:15 ===
closing AMQP connection <0.32737.44> (10.0.1.128:34526 -> 10.0.2.174:5672):
{handshake_timeout,handshake}
 ```

It times out instantly when the client connects to the server.
Any help would be really appreciated 😉 

The dockerized environment:
Server: RabbitMQ 3.6.9, Erlang 19.3
Client: Node 4.7, amqp.node 0.5.1

**Comment by cressie176** [comment]
Sorry. Too old, and too little to go on.
