### ISSUE TITLE
Allow explicit number type declaration

### ISSUE THREAD

**Issue by pcan** [amqp-node/amqplib#358]
I'm currently trying to send messages from amqp.node to a Java Spring Application, that expects an header as `long`, see this listener for example:

```Java
@RabbitListener(queues = "testQueue")
public void handleRequest(@Payload RequestBean bean, @Header("trace-id") long traceId) {
    // some logic here...
}
```

I'm getting a type mismatch exception when the `handleRequest` method gets called, since the expected type for `trace-id` is `long` (64-bit integer), but it arrives as `byte` (8-bit integer). I found that this behaviour is implemented [here](https://github.com/squaremo/amqp.node/blob/master/lib/codec.js#L163-L178), and at the moment there is no way to force the number type from outside. 

I think the codec may handle these special cases like it does for `timestamp` (see [here](https://github.com/squaremo/amqp.node/blob/master/lib/codec.js#L107-L111) and [here](https://github.com/squaremo/amqp.node/blob/master/lib/codec.js#L183-L185)), by adding `'int8'`, `'int16'`, `'int32'` and `'int64'` to that switch-case block, and let the user choose the right integer type if needed. The existing heuristic may not be changed, to avoid a breaking change.
So, I may write something like this:

```javascript
var options = {
	headers: {
		'trace-id': {'!': 'int64', value: 12}
	},
	contentType: 'application/json',
	contentEncoding: 'UTF-8'
};

channel.publish('myExchange', 'routing.key', new Buffer(JSON.stringify(message)), options);
```

**Comment by squaremo** [comment]
I like this idea. You're right that it need not interfere with the existing encodings. I'm not sure there are _signed_ 32 bit integers in AMQP 0.9.1 (or RabbitMQ's codec, anyway). But hence or otherwise, this would be fairly easy to add. PR? :)

**Comment by michaelklishin** [comment]
This is not a bad idea. Numerical type interop between languages is a pain and sometimes more control is the only way to achieve it.

On a related note, this is one of the reasons to avoid using message headers where possible and
stick to serialised message bodies.

**Comment by pcan** [comment]
Thanks. I will submit a PR asap.
