### ISSUE TITLE
Make heartbeat=60 by default

### ISSUE THREAD

**Issue by dilame** [amqp-node/amqplib#374]
This value must be defined more that 0 by default, because user could just shot yourself in the foot, as i did. 
In RabbitMQ versions 3.0 and higher, the broker will attempt to negotiate heartbeats by default every 60 seconds.
http://www.rabbitmq.com/heartbeats.html
I think it will be right if we will lead official Rabbit MQ recomendations and will not let users to shot yourself in the foot.

**Comment by michaelklishin** [comment]
Heartbeat interval is negotiated only once, when connection is opened. 

I think it's a good idea to enable heartbeats by default and use the same default timeout value as RabbitMQ and several other clients.

@squaremo WDYT?

**Comment by cressie176** [comment]
> enable heartbeats by default and use the same default timeout value as RabbitMQ

@michaelklishin I think this is the current behaviour. amqplib's default is 0, which means use the server setting. Since RabbitMQ's default is 60 seconds, heartbeats will be enabled by default, at least for current versions. Maybe it wasn't always this way.

**Comment by michaelklishin** [comment]
Yes, `0` is a really unfortunate default.

I'd recommend a default of 10-30 seconds. RabbitMQ server and official clients cannot easily change this default after more than a decade but chances are it might go lower than 60s there, too. As the Heartbeats guide states, values < 5s are asking for false positives, so let's not get too excited :)

**Comment by cressie176** [comment]
Now I'm confused - the original suggestion was to make the heartbeat 60s by default, which it already is because unless overridden, the client uses the server default, which is also 60s. However, your recent post suggests 10-30 seconds.

**Comment by michaelklishin** [comment]
Team RabbitMQ has arrived at the conclusion that values in the [10s, 30s] range are optimal, that's all. 60s is a much better default than 0.

The reason why we cannot quickly change the default across the board is mentioned above: the project is over 15 years old. There are all kinds of systems that may unintentionally depend on a particular value.

I personally don't feel strongly about this, if you'd like to leave the 60s default as is.

**Comment by cressie176** [comment]
I'm going to close. It doesn't sit well to change from defaulting to what may have been a carefully configured server value. Happy to reconsider if I've misunderstood or there's a strong case.
