### ISSUE TITLE
Numeric headers don't work with headers exchanges

### ISSUE THREAD

**Issue by aalexgabi** [amqp-node/amqplib#384]
After searching for a while it seems that amqplib does not work when trying to publish a message routed based on a numeric header for a headers exchange.

To reproduce:
1. Create a queue in RMQ UI
2. Create a headers exchange in RMQ UI
3. Create a binding based on a numeric header value between the queue and the exchange in RMQ UI
4. Publish a message with the binded numerical value in RMQ UI
4. Publish a message with the binded numerical value using amqplib

Only the message published in RMQ UI will be present

Probably related: https://github.com/squaremo/amqp.node/issues/358 https://github.com/squaremo/amqp.node/pull/359

Tested with 0.5.1

**Comment by cressie176** [comment]
Seems to work now. The following generates two random numbers, then binds a queue to a header exchange using the first one. It publishes a message for each number, then checks that only one is routed to the queue.

```javascript
const amqp = require('amqplib');
const assert = require('assert');

(async () => {

  const value1 = Math.random();
  const value2 = Math.random();

  const connection = await amqp.connect();
  const channel = await connection.createConfirmChannel();
  await channel.assertQueue('test-q');
  await channel.purgeQueue('test-q');
  await channel.assertExchange('test-ex', 'headers');
  await channel.bindQueue('test-q', 'test-ex', '', {
    'x-match': 'any',
    key: value1
  });

  await publishAll([value1, value2]);
  await assertMessage(value1);
  await assertEmpty();

  await channel.close();
  await connection.close();

  async function publishAll(values) {
    values.forEach(publish);
    return channel.waitForConfirms();
  }

  function publish(value) {
    channel.publish('test-ex', '', Buffer.from(`Message ${value}`), {
      headers: {
        key: value
      }
    });
  }

  async function assertMessage(value) {
    const message = await channel.get('test-q');
    assert(message);
    assert(message.content.toString() === `Message ${value}`);
  }

  async function assertEmpty() {
    const message = await channel.get('test-q');
    assert(message === false);
  }
})();
```
