### ISSUE TITLE
Mixing Event Emitter Events with Async/Await

### ISSUE THREAD

**Issue by dstibrany** [amqp-node/amqplib#397]
I'm trying to figure out the best way to handle channel/connection errors and events within the context of a try/catch block.

Ideally I'd have something like:
```
try {
  await setupConnection();
  await setupChannel(); // event emitters such as channel.on('error') are defined in this function
  while (true) {
    await consume();
    await doWork();
    ...
  }
} catch (e) {
  handleError(e);
}
```

Then, I would throw errors from my event emitters and could then handle all errors, connection closes, etc. in one place.

This doesn't seem to work, however. Is there a better way of doing this?

**Comment by cressie176** [comment]
Hi @dstibrany,

What doesn't work? I think provided you throw errors under the following scenarios

1. connection.on('error')
1. connection.on('close')
1. channel.on('error')
1. channel.on('close')

and guard against multiple events per incident (e.g. you may get both a close and error event) you should be able to get this working.

You should also be prepared that your consumer will get a null message when the channel is closed.
