### ISSUE TITLE
Publish after disconnect the network

### ISSUE THREAD

**Issue by showerhan** [amqp-node/amqplib#400]
I published a message after I disconnected the network. It returned true. How can I judge the channel is not working correctly right now?  I tried heartbeat option with value 1, but there are still 2 seconds. I can't catch  any exceptions during these two seconds if I publish messages.  Is that a problem or I'm misunderstanding?

**Comment by michaelklishin** [comment]
Use [publisher confirms](http://www.rabbitmq.com/confirms.html). Please read [this doc guide](http://www.rabbitmq.com/heartbeats.html) to understand the fundamental problem, too.

**Comment by showerhan** [comment]
@michaelklishin  Thank you. Do you mean I should use ConfirmChannel?

**Comment by michaelklishin** [comment]
It doesn't matter what API you use as long as you understand the purpose of and use the feature. There is an [example available](https://github.com/squaremo/amqp.node/blob/master/examples/waitForConfirms.js) in this repository. This is just one possible way of using this feature, there can be others.

**Comment by showerhan** [comment]
Although publish returned true, the message was not sent. Is there a way I can be notified in this case? I'm afraid publisher confirms didn't help.

**Comment by cressie176** [comment]
All publisher confirms tell you is that the message was received by the broker. There is no guarantee how long they will take (although it is usually milliseconds), and if the message or the reply is lost, then you will never receive the confirmation. Even if you were to receive notification that the channel or connection died after sending, it is still possible that the broker received the message. While it may be possible to narrow the chances of this happening further improving amqplib, there will always be the chance.

Therefore the application developer needs to make a choice about what to do if a confirmation is not received within what a reasonable time frame. For example, you may choose to emit or yield an error if a timeout expires indicating that the fate of the message is unknown. In a busy publisher this may increase both memory usage and the size of the event loop however.

There is some more discussion on the subject [here](https://github.com/amqp-node/amqplib/issues/419)
