### ISSUE TITLE
A timeout option for channel.get?

### ISSUE THREAD

**Issue by ling1726** [amqp-node/amqplib#415]
Hello,

I have a use case where it would be great to long poll for a reply message from a server application. This is for a CLI where one command will send a message and expect one reply only.

 Currently Implement this myself with a custom promise like so: 

````
function _pollMessage(timeout){
    let start = (new Date()).getTime();
    console.log(`start polling for message, timeout in ${timeout} millisecods`);
    let whileNotTimeout = () => {
        return channel.get(queue, {noAck: true}).then(function(res) {
            let current = (new Date().getTime());
            if(current-start>timeout) throw new Error('TIMEOUT');

            if (res === false) {
                 // run the operation again
                 return whileNotTimeout();
            } else {
                console.log('message received');
                return res;
            }
        });
    }

    return whileNotTimeout();
}
````
What do you think? if there is a better way of doing it, please let me know

**Comment by cressie176** [comment]
LGTM. I would use `Date.now()` rather than `new Date().getTime()` and consider adding a setTimeout with a very small delay rather than retrying immediately. Otherwise all good.
