### ISSUE TITLE
Additional maintainers

### ISSUE THREAD

**Issue by kibertoad** [amqp-node/amqplib#418]
Given that this project is very quiet lately and it doesn't look like anyone is addressing PRs that get piled up, it would probably be most helpful if there were additional maintainers with write permissions who could review, approve and merge PRs.

**Comment by Stradivario** [comment]
i agree

**Comment by yaronlevi** [comment]
So this project is not actively maintained

**Comment by cressie176** [comment]
> So this project is not actively maintained?

I think that depends on what you mean by active. The AMQP 0-9-1 protocol was in published in November 2008, so this module doesn't have much need to be updated frequently. Despite this version 0.5.2 was released in November 2017. There's a reasonable response rate to issues. Given the amqp.node protocol is complicated and bug ridden I can understand some reluctance to add more maintainers with write permissions.

**Comment by kibertoad** [comment]
@cressie176 However, when community creates something useful like #411, it is really unfortunate when there is noone around to review it. Don't get me wrong, I am very grateful to the author for all the hard work he has been putting into the project over the years, all I am worried about is project stagnating due to lack of gatekeepers around.

**Comment by squaremo** [comment]
> Given that this project is very quiet lately and it doesn't look like anyone is addressing PRs that get piled up, it would probably be most helpful if there were additional maintainers with write permissions who could review, approve and merge PRs.

I think that's a fair statement. To clear thing up: I have not abandoned amqplib, I just have very little time to spend on it.

It would be good to have additional maintainers. How shall I pick them?

**Comment by michaelklishin** [comment]
@squaremo team RabbitMQ tried to get in touch and ask for commit rights for this project for at least a couple of us. Some users of this client are much more active in Github issues than others @cressie176 comes to mind.

I don't know if "several weeks" is a reasonable response rate. If my response rate for a project is weeks I always add most active users as committers. This client badly needs some quality time (like no other) and team RabbitMQ is happy to offer some. We are not JavaScript experts but we have more experience maintaining RabbitMQ clients than any other team on this planet.

**Comment by michaelklishin** [comment]
Besides the core team this project badly needs an issue cleanup. Most of the open issues are questions, some are basic, that should be closed, labelled as such and answered if there's enough information to work with. The rest will be triaged to see if they are legitimate and can be addressed.

At some point maintainers will have to produce new releases, which means they must have push permissions on NPM and potentially more services.

**Comment by cressie176** [comment]
@michaelklishin when I said the protocol was bug ridden and complicated I was referring to https://www.rabbitmq.com/amqp-0-9-1-errata.html. Sorry, I should have been more clear.

WRT picking additional maintainers, I can't imagine anyone better than the RabbitMQ team. I'd also be happy to help out WRT closing issues and reviewing / accepting some PRs. I'm wouldn't trust myself to work on the code base.

**Comment by xamgore** [comment]
@michaelklishin are you still ready to provide help? I would like to discuss features the library lacks in comparison to other client implementations.

```js
"clientProperties": {
    "capabilities": {
      "publisher_confirms": true,
      "exchange_exchange_bindings": true,
      "basic.nack": true,
      "consumer_cancel_notify": true,
      "connection.blocked": true,
      "authentication_failure_close": true
    }
}
```

Soon, I'll send a few PRs with migration to jest and fast-check (instead of mocha and claire), and the next with migration to typescript.

**Comment by paul-bell** [comment]
Greetings. I today find that I could make good use of clientProperties support in amqplib.

Does anyone know if any progress has been made in this direction?

Thank you.

-Paul
