### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by sekys** [amqp-node/amqplib#476]
Hello guys,

last days I had trouble with `ECONNRESET` error. I was not able connect to the server. I consult problem at [RabbitMQ group](https://groups.google.com/forum/#!topic/rabbitmq-users/C-FRSDzO1_c).
At the end i find that this library have problem with **pmx** library 0.5.5. Probably **pmx** somehow block socket to the server or something like that. I think that this is also **amqplib** problem. Like a library should print something about blocket socket. Old **amqp** library was able to connect or reconnect.

```
const pmx = require('pmx');

pmx.init({
	network: true,
	ports: true,
});
```

**Comment by cressie176** [comment]
Hi @sekys,

Appreciate this is rather late, but I have no issues connecting to RabbitMQ server using amqplib@0.5.5 with pmx@1.6.7 initialised as you describe (or with the default config)

I tested by adding this following line to [this](https://github.com/cressie176/amqplib-express-example/blob/master/index.js#L1) example
```
const pmx = require('pmx').init({ network: true, ports: true });
```
and launching via `pm2 start index.js`

However I've never used pmx before and didn't try connecting to a broker running in AWS so may be missing something.
