### ISSUE TITLE
Can we configure the outgoing port?

### ISSUE THREAD

**Issue by philippefutureboy** [amqp-node/amqplib#491]
Hi!

I'm currently investigating using amqp.node as my choice of client library for an MQ. My client application is installed on a remote machine that is behind a firewall. Hence, only a specific set of ports are open on the machine.

Is it possible to configure the TCP socket port that amqp.node uses when establishing a connection to the message queue? I couldn't find anything in the documentation in that regards.

Thanks for your answer! ☀️

Cheers,

Philippe

**Comment by squaremo** [comment]
The firewall filters based on the source port? That's pretty unusual isn't it?

**Comment by philippefutureboy** [comment]
Thanks for the question, allowed me to clarify things on my side ~

While you are right, it seems like it is possible. In high security environments, a firewall can be setup to block any outgoing traffic to [limit what an attacker can do once they've compromised a system on your network](https://security.stackexchange.com/a/24313).

The question on my side comes from the fact that the computers on which my client applications run are generally behind their own VPN and have some pretty strict firewall rules. As such, is it possible to configure the TCP socket port that amqp.node uses when establishing a connection to the message queue? That could allow me to settle for a port that is configured to be open

**Comment by cressie176** [comment]
Not related to your question or this library, but worth being aware of...

I’ve had problems with amqp / rabbitmq and VPN/Firewalls - the protocol establishes a permanent connection which may be closed by the VPN/Firewall, especially in the event of no traffic. 

You can mitigate this by configuring heartbeats and designing the client to automatically recover

**Comment by cressie176** [comment]
Looks like you can set the outgoing port using socketOptions...

```js
const connection = await amqplib.connect('amqp://localhost?heartbeat=5', { localPort: 64112 });
```
