### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by house92** [amqp-node/amqplib#512]
To outline our app:

- node 8.9.0
- two connections (publish and consume)
- two channels (publish and consume)
- data is retrieved from various endpoints
- data is split into objects, each of which is published/consumed as its own message
- several queues along the pipeline, with services handling the data in different ways between each
- the penultimate service also touches a SQL database
- prefetch limit of 10

We first observed a gradual memory creep followed by a spike, and having recorded the memory heap allocation using Chrome dev tools it appears that this is related to the `Mux` class, being called inside `Connection`. We end up with many streams that are nested hundreds of thousands of times, totalling over 200MB.

Before delving deeper, I wanted to check with you what the function of the `Mux` class is and whether this sounds like a symptom of our misuse of the library or an area for potential optimisation within your code. If the latter, I’m still happy to fork the repo and look into it, but any clarification would be very welcome.

**Comment by squaremo** [comment]
`Mux` is for multiplexing frames from channels onto the single connection. It is definitely concerning if it appears to hold references.

Do you reckon you can come up with a minimal example that shows the behaviour? (Are there any preconditions other than say, using more than one channel?)

How are the nested streams nested?

**Comment by house92** [comment]
Sorry for the slow reply @squaremo. I'll have a think about how I could replicate this without using private code, but I would also point out that we only observe this under reasonably heavy load.

The streams are nested in as much as each stream has a `next` field that references the next stream. However, it seems strange that there should be so much data that so many streams need to be chained together.

**Comment by timcosta** [comment]
@house92 did y'all ever figure out the solution to this issue?

**Comment by Uzlopak** [comment]
Maybe #658 improves the memory footprint.

**Comment by cressie176** [comment]
I've run the following script using `node --max-old-space-size=64 index.js ` for several minutes...

```javascript
const random = require('random-readable');
const { v4: uuid } = require('uuid')
const amqplib = require('amqplib');

(async () => {
  const stats = { published: 0, received: 0 }

  const publisherConnection = await amqplib.connect('amqp://localhost');
  const publisherChannel = await publisherConnection.createChannel();
  await publisherChannel.assertQueue('test', { durable: false, autoDelete: true });

  const consumerConnection = await amqplib.connect('amqp://localhost');
  const consumerChannel = await consumerConnection.createChannel();
  const consumerTag = uuid();

  await consumerChannel.consume('test', (message) => {
    dumpStats();
    consumerChannel.ack(message);
    stats.received++;
  }, { noAck: false, consumerChannel });

  const stream = random
    .createRandomStream()
    .on('error', console.error)
    .on('data', (data) => {
      const ok = publisherChannel.sendToQueue('test', data);
      if (!ok) stream.pause();
      stats.published++;
    })
    .on('end', () => {
      console.log('end');
    });

  publisherChannel.on('drain', () => {
    stream.resume();
  })

  process.once('SIGINT', async () => {
    stream.pause();
    publisherChannel.removeAllListeners('drain');
    publisherChannel.on('drain', async () => {
      await publisherChannel.close();
      await publisherConnection.close();
    })
    await consumerChannel.cancel(consumerTag);
    await consumerChannel.close();
    await consumerConnection.close();

    dumpStats();

    process.exit(0);
  })

  function dumpStats() {
    process.stdout.clearLine(0);
    process.stdout.cursorTo(0);
    process.stdout.write(`published: ${stats.published}, received: ${stats.received}`);
  }
})();
```
The total memory footprint of the node process stayed at under 90MB. I realise this is an old issue, but am wondering if you ever got to the bottom of it. Could the problem have been that when under high load, your application was receiving more work than it could handle? You'll see in the above example I'm careful to pause the stream, so that I don't flood the publisher channel.

**Comment by cressie176** [comment]
Closing as an old issue and unable to reproduce
