### ISSUE TITLE
Failed "connect" call does not close socket

### ISSUE THREAD

**Issue by rumata28** [amqp-node/amqplib#513]
I am developing integration tests and have problems with negative case testing - my test app never exits.

Steps to Reproduce:
* Call connect to vhost, for which user does not have permissions
* See that err callback is called
* See that NodeJS app just hangs, never exits.

I found that reason is that the following block is only called on timeout:
```
        sock.end();
        sock.destroy();
```
And it is never called on other connection errors.

**Comment by aknrdureegaesr** [comment]
# Processing leak after rejection

We had a similar problem with an integration test. In our case, the symptom: `connect()` produces a `Promise` (or, more precisely, a `BlueBird`) which is duly rejected a bit later. Our test waits for that rejection to happen. So far, so well. But then, the test framework complains that some background activity is still ongoing, even though the test has finished.

Our expectation is: At the time the promise rejects, all resources have been freed and all background processing pertaining the connection attempt has ceased. Our test framework (we use Jest) waits for another second, and in that second, not all background processing has terminated.

## Details

We have a standard RabbitMQ running via

```
docker run --rm -ti -p 127.0.0.1:5672:5672 -p 127.0.0.1:15672:15672 rabbitmq:3-management
```

and try to connect to it, using the default existing user and password, but also using a vhost that does not exist.

The pertinent part of our (typescript) code is this:

```
  const connectionConfig: Options.Connect = {
    protocol: 'amqp',
    hostname: 'localhost',
    port: 5672,
    username: 'guest',
    password: 'guest',
    heartbeat: 2,
    vhost: 'no_such_vhost',
  };
  const amqplibConnection = connect(connectionConfig);
  await expect(amqplibConnection).rejects.toThrowError();
  ```

**Comment by cressie176** [comment]
amqplib v0.9.0 includes [PR 647](https://github.com/squaremo/amqp.node/pull/647) which ends and destroys the socket.
