### ISSUE TITLE
"value" argument is out of bounds

### ISSUE THREAD

**Issue by krisalay** [amqp-node/amqplib#515]
Hello,
I am getting the "value argument is out of bounds" error.
The following is the error stack.

```
TypeError: "value" argument is out of bounds
  File "/app/node_modules/buffer-more-ints/buffer-more-ints.js", line 52, col 15, in check_value
    throw new TypeError("\"value\" argument is out of bounds");
  File "/app/node_modules/buffer-more-ints/buffer-more-ints.js", line 322, col 11, in Object.writeInt64BE
    val = check_value(val, -0x800000000000000000, 0x7fffffffffffffff);
  File "/app/node_modules/amqplib/lib/codec.js", line 204, col 14, in encodeFieldValue
    ints.writeInt64BE(buffer, val, offset); offset += 8;
  File "/app/node_modules/amqplib/lib/codec.js", line 85, col 21, in encodeTable
    offset += encodeFieldValue(buffer, val[key], offset);
  File "/app/node_modules/amqplib/lib/defs.js", line 1297, col 9, in encodeQueueDeclare
    len = encodeTable(SCRATCH, val, scratchOffset);
  File "/app/node_modules/amqplib/lib/defs.js", line 3429, col 12, in module.exports.encodeMethod
    return encodeQueueDeclare(channel, fields);
  File "/app/node_modules/amqplib/lib/connection.js", line 530, col 15, in Connection.C.sendMethod
    var frame = encodeMethod(Method, channel, fields);
  File "/app/node_modules/amqplib/lib/channel.js", line 64, col 26, in Channel.C.sendImmediately
    return this.connection.sendMethod(this.ch, method, fields);
  File "/app/node_modules/amqplib/lib/channel.js", line 443, col 12, in Channel.C.accept
    this.sendImmediately(send.method, send.fields);
  File "/app/node_modules/amqplib/lib/connection.js", line 64, col 33, in Connection.mainAccept [as accept]
    if (rec) { return rec.channel.accept(frame); }
  File "/app/node_modules/amqplib/lib/connection.js", line 478, col 48, in Socket.go
    var f; while (f = self.recvFrame()) self.accept(f);
  File "events.js", line 189, col 13, in Socket.emit
  File "domain.js", line 441, col 20, in Socket.EventEmitter.emit
  File "_stream_readable.js", line 535, col 12, in emitReadable_
  File "internal/process/next_tick.js", line 63, col 19, in process._tickCallback
```
Nodejs version: 10
amqplib version: ^0.5.3

What is this error, and how do i resolve it?

**Comment by cressie176** [comment]
Hi @krisalay. Can you paste your code please?

**Comment by krisalay** [comment]
`export class Amqp {
  public amqpConn: amqp.Connection = null;
  public channel: amqp.Channel;
  public async start(retries?: number) {
    try {
      this.amqpConn = await amqp.connect(process.env.RABBIT_HOST || "localhost");
      console.info("[AMQP] connected");
      this.channel = await this.amqpConn.createChannel();
      this.channel.prefetch(50);
      await this.configureQueues("queue1");
      await this.configureQueues("queue2");
      await this.configureQueues("queue3");
      await this.configureQueues("queue4");
      await this.connectionSuccessful();
      console.log("[AMQP] channel started");
      if (!retries) {
        retries = 5;
      }
      this.amqpConn.on("error", (err) => {
        console.info(err);
        if (err.message !== "Connection closing") {
          console.info("[AMQP Error]");
        }
      });
      this.amqpConn.on("close", () => {
        console.info("[AMQP] reconnecting");
        if (retries === 0) {
          // TODO: send notification to admin
        }
        retries--;
        return setTimeout(async () => {
          await this.start(retries);
        }, 2000);
      });
    } catch (e) {
      if (retries === 0) {
        // TODO: send notification to admin
      }
      console.info("[AMQP Error]", e.message);
      retries--;
      return setTimeout(async () => {
        await this.start(retries);
      }, 2000);
    }
  }
  private async connectionSuccessful() {
    await AmqpWorker.start(this.channel, 4, "queue1", Worker1.start);
    await AmqpWorker.start(this.channel, 4, "queue2", Worker2.start);
    await AmqpWorker.start(this.channel, 4, "queue3", Worker3.start);
    await AmqpWorker.start(this.channel, 4, ""queue4", Worker4.start);
  }

  private async configureQueues(queueName) {
    return Promise.all([]
      .concat(this.channel.assertExchange(`${queueName}-exchange`, "fanout", { durable: true }))
      .concat(this.channel.assertExchange(`${queueName}-ttl`, "direct", { durable: true }))
      .concat(this.channel.assertExchange(`${queueName}-dlx`, "fanout", { durable: true }))
      .concat(this.channel.assertQueue(queueName, { durable: true }))
      .concat([
        this.channel.assertQueue(`${queueName}-retry-1-300s`, { durable: true, deadLetterExchange: `${queueName}-dlx`, messageTtl: parseInt(process.env.RETRY_1, 10) }),
        this.channel.assertQueue(`${queueName}-retry-2-900s`, { durable: true, deadLetterExchange: `${queueName}-dlx`, messageTtl: parseInt(process.env.RETRY_2, 10) }),
        this.channel.assertQueue(`${queueName}-retry-3-2700s`, { durable: true, deadLetterExchange: `${queueName}-dlx`, messageTtl: parseInt(process.env.RETRY_3, 10) })
      ])
      .concat(this.channel.bindQueue(queueName, `${queueName}-exchange`, "#"))
      .concat(this.channel.bindQueue(queueName, `${queueName}-dlx`, "#"))
      .concat([
        this.channel.bindQueue(`${queueName}-retry-1-300s`, `${queueName}-ttl`, "retry-1"),
        this.channel.bindQueue(`${queueName}-retry-2-900s`, `${queueName}-ttl`, "retry-2"),
        this.channel.bindQueue(`${queueName}-retry-3-2700s`, `${queueName}-ttl`, "retry-3")
      ])
    );
  }
}
`

The message flows from Worker1 -> Worker2 -> Worker3 -> Worker4

**Comment by krisalay** [comment]
@cressie176 
Can you please let me know, what's the issue?

**Comment by cressie176** [comment]
My first guess would be you're missing one or more of the RETRY_N environment variables. Consequently the messageTtl would be NaN, which might explain why there was a conversion error attempting to write an integer during queue declaration.
```
this.channel.assertQueue(`${queueName}-retry-1-300s`, { durable: true, deadLetterExchange: `${queueName}-dlx`, messageTtl: parseInt(process.env.RETRY_1, 10) }),
this.channel.assertQueue(`${queueName}-retry-2-900s`, { durable: true, deadLetterExchange: `${queueName}-dlx`, messageTtl: parseInt(process.env.RETRY_2, 10) }),
this.channel.assertQueue(`${queueName}-retry-3-2700s`, { durable: true, deadLetterExchange: `${queueName}-dlx`, messageTtl: parseInt(process.env.RETRY_3, 10) })
```

Not related, but I think there's a bug here too...
```
if (!retries) {
  retries = 5;
}
```
if retries = 0, then the code will reset it to 5

**Comment by krisalay** [comment]
@cressie176 
I checked on the rabbitmq dashboard, and for each of the retry queue, the values are set to integral values. Do you think there may be some issue with the credits management for the rabbitmq?

Also, thanks for pointing the error in the retry.

**Comment by cressie176** [comment]
@krisalay just because the queues already exist and are defined correctly in the RabbitMQ console doesn't mean the code isn't failing as I suggested. For example, the environment variables could have been set when the code first ran, thus creating the queues, but if your application runs on multiple servers or was redeployed they might not have been present on later runs.

I put together the following test case and code a similar stack trace
```
const amqp = require('amqplib');
  
amqp.connect().then((connection) => {
  connection.createChannel().then((channel) => {
    channel.assertQueue('bar', { durable: true, messageTtl: parseInt(undefined, 10) }).then(() => {
     console.log("ok");
    });
  })
});
```

```
Unhandled rejection TypeError: "value" argument is out of bounds
    at check_value (/Users/steve/issue515/node_modules/buffer-more-ints/buffer-more-ints.js:52:15)
    at Object.writeInt64BE (/Users/steve/issue515/node_modules/buffer-more-ints/buffer-more-ints.js:322:11)
    at encodeFieldValue (/Users/steve/issue515/node_modules/amqplib/lib/codec.js:204:14)
    at encodeTable (/Users/steve/issue515/node_modules/amqplib/lib/codec.js:85:21)
    at encodeQueueDeclare (/Users/steve/issue515/node_modules/amqplib/lib/defs.js:1297:9)
    at module.exports.encodeMethod (/Users/steve/issue515/node_modules/amqplib/lib/defs.js:3429:12)
    at Connection.C.sendMethod (/Users/steve/issue515/node_modules/amqplib/lib/connection.js:530:15)
    at Channel.C.sendImmediately (/Users/steve/issue515/node_modules/amqplib/lib/channel.js:64:26)
    at Channel.C.sendOrEnqueue (/Users/steve/issue515/node_modules/amqplib/lib/channel.js:75:10)
    at Channel.C._rpc (/Users/steve/issue515/node_modules/amqplib/lib/channel.js:136:8)
    at /Users/steve/issue515/node_modules/amqplib/lib/channel_model.js:59:17
    at tryCatcher (/Users/steve/issue515/node_modules/bluebird/js/release/util.js:16:23)
```

**Comment by krisalay** [comment]
ok, I will check it and let you know if that solves the issue.
Btw, thanks for your help. :)

**Comment by krisalay** [comment]
@cressie176 
I checked it, also I made the values to be constant as 300000, 900000, and 2700000 for retry1, retry2, retry3 respectively. But still the issue persists.

**Comment by cressie176** [comment]
Hi @krisalay,

If I update my code to the following I no longer see the error. Can you try this code in your environment?

```
amqp.connect().then((connection) => {
  connection.createChannel().then((channel) => {
    channel.assertQueue('queue1-retry-1-300s', { durable: true, messageTtl: 300000 }).then(() => {
     console.log("ok");
    });
  }) 
});
```

You could try executing the promises sequentially instead of concurrently. With your current setup you could be binding to queues and exchanges that hadn't actually been created yet. I don't think this will be the cause of the issues however, since it sounds like the objects have been created by an earlier run.

**Comment by cressie176** [comment]
Did you manage to resolve the problem @krisalay?
