### ISSUE TITLE
ConfirmChannel.publish does not fail (or hangs) if RabbitMQ gets lost

### ISSUE THREAD

**Issue by hardcodet** [amqp-node/amqplib#530]
Short version:

Problem: I want a `publish` to fail immediately so that clients know that they need to retry a send. If the RabbitMQ server goes down, amqp doesn't tell me that a publish failed, even on a ConfirmChannel, but hangs forever.

Long version:

Not sure whether I'm looking at a bug here: It appears that a `publish` does not report an error when I publish a message if RabbitMQ just went down. This results in my clients thinking everything is fine, when it's actually not at all guaranteed that a message will ever even make it to the server.

I tried the following:
- using confirmChannel
- submitting a callback: The callback is only invoked if a connection to RabbitMQ exists
- awaiting `channel.waitForConfirms()` seems to hang forever

Repro:

1. start app with a healthy RabbitMQ server
2. connect and create a confirmChannel
3. kill the RabbitMQ server (app keeps running)
4. publish a message before the heartbeats detect that the connection is gone
5. `publish` will still return true (!), but the callback will not be invoked. Alternatively, invoking `awaitForConfirms` will hang indefinitely.

Here's my code (with both the callback/await versions, just comment out what you don't need)

    public async publish(exchangeName: string, content: object, headers?: object) {

        try {
            const data = Buffer.from(JSON.stringify(content));

            // publish the message, and escalate in case of a failure
            console.log("publishing...");
            const status: boolean = this.channel.publish(exchangeName, "", data, { persistent: true, timeout: 2000, headers: headers || {} }, (err, ok) => {
                // I never get here with a severed connection
                console.log("ACK PUBLISH - err " + err + ", ok: " + ok);
            });

            await this.channel.waitForConfirms();
            console.log("CONFIRMS"); //i never get there with the await in place, if the connection is gone

            if (!status) {
                // will be logged and rethrown
                throw new Error(`Publishing message to exchange ${exchangeName} failed with status ${status}.`);
            }
        } catch (e) {
            this.logger.error("Could not publish message to exchange.", e, {
                name: "mqPayload",
                exchange: exchangeName,
                headers: headers || null,
                ...content,
            });
            throw e;
        }
    }

**Comment by hardcodet** [comment]
Potentially related to https://github.com/squaremo/amqp.node/issues/419

**Comment by simuty** [comment]
I have the same question

**Comment by simuty** [comment]
**i hope this useful**

[channel_events](http://www.squaremobius.net/amqp.node/channel_api.html#channel_events)
createConfirmChannel callback can catch error such as code ⬇️


```js
async function publish(msg: string, connect: amqp.Connection) {
    const exchange = '5.confirm.exchange';
    const exchangeType = 'direct';
    const routingKey = '5.confirm.routingKey';

    const channel = await connect.createConfirmChannel();
    await channel.assertExchange(exchange, exchangeType, { durable: false })
    const content = JSON.stringify({ msg });
    const random = Math.random() < 0.4;

    if (random) {
        channel.close()
    }
    channel.publish(exchange, routingKey, Buffer.from(content), {}, (err, ok) => {
        if (err !== null) {
// this will catch channel.close() error
            console.log('error---', err);
        } else {
            console.log('suc---', err, ok, content);
        }
    });
// if you set mandatory: true , but no queue, this will catch
   channel.on('return', (args)=>{
        console.log("return: ", args);
    })
    channel.on('error', (args)=>{
        console.log("error: ", args);
    })
    channel.on('close', (args)=>{
        console.log("close: ", args);
    })
    await channel.waitForConfirms()
    await channel.close();
}


(async function testConfirmChannel() {
    const url = `amqp://localhost`;
    const connect = await amqp.connect(url)
    let index = 0;

    while (index < 4) {
        index++;
        await retryTest(index, 3);
    }
    async function retryTest(index: number, retryTime: number) {
        try {
            console.log(`send ${index}`);
            await publish(`send ${index}`, connect);
        } catch (error) {
            if (retryTime > 0) {
                await sleep(3);
                console.log(`${index} retry, num: ${retryTime}`)
                await retryTest(index, retryTime - 1)
            } else {
                console.error(`🚩🚩🚩 ${index} need handle`);
            }
        }
    }
    process.exit(0);
})();


function sleep(time: number) {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(true)
        }, time * 1000);
    })
}

```

**Comment by cressie176** [comment]
I believe the behaviour the OP desires is only possible if you you don't share channels when publishing messages. If you do this, then you can register an error handler on the channel which if triggered can inform the caller of the problem. After successfully receiving the publisher confirm, the error handler should be removed.

You can take a similar approach for timeouts, i.e. prior to publishing setup a timeout, and if the timeout expires inform the caller. However you should be aware that the message may still be delivered and your code may still receive the delayed publisher confirm.

The downside of this approach is that performance will suffer. I attempted to solve this by using a channel pool, but publishing is still far slower than sharing channels.

Closing as this issue is several years old.
