### ISSUE TITLE
I cannot find nowait option in assert options

### ISSUE THREAD

**Issue by actumn** [amqp-node/amqplib#542]
We can find nowait option in decalre api in rabiitmq 
[exchange declare](https://www.rabbitmq.com/amqp-0-9-1-reference.html#exchange.declare.no-wait)
[queue declare](https://www.rabbitmq.com/amqp-0-9-1-reference.html#queue.declare.no-wait)
And there is `nowait` option in [amqp-rabbitmq-0.9.1.json](https://github.com/rabbitmq/rabbitmq-codegen/blob/master/amqp-rabbitmq-0.9.1.json)
```json
{
    "id": 40,
    "methods": [{"id": 10,
                  "arguments": [{"type": "short", "name": "ticket", "default-value": 0},
                                {"type": "shortstr", "name": "exchange"},
                                {"type": "shortstr", "name": "type", "default-value": "direct"},
                                {"type": "bit", "name": "passive", "default-value": false},
                                {"type": "bit", "name": "durable", "default-value": false},
                                {"type": "bit", "name": "auto-delete", "default-value": false},
                                {"type": "bit", "name": "internal", "default-value": false},
                                {"type": "bit", "name": "nowait", "default-value": false},
                                {"type": "table", "name": "arguments", "default-value": {}}],
                  "name": "declare",
                  "synchronous" : true},
                 
{
    "id": 50,
    "methods": [{"id": 10,
              "arguments": [{"type": "short", "name": "ticket", "default-value": 0},
                {"type": "shortstr", "name": "queue", "default-value": ""},
                            {"type": "bit", "name": "passive", "default-value": false},
                            {"type": "bit", "name": "durable", "default-value": false},
                            {"type": "bit", "name": "exclusive", "default-value": false},
                            {"type": "bit", "name": "auto-delete", "default-value": false},
                            {"type": "bit", "name": "nowait", "default-value": false},
                            {"type": "table", "name": "arguments", "default-value": {}}],
              "name": "declare",
              "synchronous" : true},
              
```
  
But when I install amqplib from npm, I cannot find nowait option in amqplib/properties.d.ts
```typescript
interface AssertQueue {
    exclusive?: boolean;
    durable?: boolean;
    autoDelete?: boolean;
    arguments?: any;
    messageTtl?: number;
    expires?: number;
    deadLetterExchange?: string;
    deadLetterRoutingKey?: string;
    maxLength?: number;
    maxPriority?: number;
}

interface AssertExchange {
    durable?: boolean;
    internal?: boolean;
    autoDelete?: boolean;
    alternateExchange?: string;
    arguments?: any;
}
```

Can anyone check it?

**Comment by KristjanTammekivi** [comment]
I believe RabbitMQ ignores nowait on queue/exchange declarations

**Comment by cressie176** [comment]
I tested this using the following script and using wireshark to see whether the broker replied to the queue declare.

```js
const amqplib = require('amqplib');

(async () => {
  const connection = await amqplib.connect();
  const channel = await connection.createChannel();
  await channel.assertQueue('test');
  await connection.close();
})();
```
because amqplib hardcodes nowait to false, the broker replies with a Queue.Delcare-OK 

```
7	0.004101	127.0.0.1	127.0.0.1	AMQP	569	Connection.Start 
9	0.006407	127.0.0.1	127.0.0.1	AMQP	377	Connection.Start-Ok 
11	0.007467	127.0.0.1	127.0.0.1	AMQP	76	Connection.Tune 
13	0.007915	127.0.0.1	127.0.0.1	AMQP	76	Connection.Tune-Ok 
15	0.008066	127.0.0.1	127.0.0.1	AMQP	72	Connection.Open vhost=/ 
17	0.008916	127.0.0.1	127.0.0.1	AMQP	69	Connection.Open-Ok 
19	0.012571	127.0.0.1	127.0.0.1	AMQP	69	Channel.Open 
21	0.014028	127.0.0.1	127.0.0.1	AMQP	72	Channel.Open-Ok 
23	0.014766	127.0.0.1	127.0.0.1	AMQP	80	Queue.Declare q=test 
25	0.015821	127.0.0.1	127.0.0.1	AMQP	81	Queue.Declare-Ok q=test 
27	0.016229	127.0.0.1	127.0.0.1	AMQP	89	Connection.Close reply=Cheers, thanks 
29	0.017239	127.0.0.1	127.0.0.1	AMQP	68	Connection.Close-Ok 
```
However, if I change my locally installed amqplib library to force nowait to true, no reply is sent and the `channel.assertQueue` never resolves.

```javascript
58	77.481049	127.0.0.1	127.0.0.1	AMQP	569	Connection.Start 
60	77.483636	127.0.0.1	127.0.0.1	AMQP	377	Connection.Start-Ok 
62	77.484767	127.0.0.1	127.0.0.1	AMQP	76	Connection.Tune 
64	77.485195	127.0.0.1	127.0.0.1	AMQP	76	Connection.Tune-Ok 
66	77.485345	127.0.0.1	127.0.0.1	AMQP	72	Connection.Open vhost=/ 
68	77.486269	127.0.0.1	127.0.0.1	AMQP	69	Connection.Open-Ok 
70	77.490569	127.0.0.1	127.0.0.1	AMQP	69	Channel.Open 
72	77.492391	127.0.0.1	127.0.0.1	AMQP	72	Channel.Open-Ok 
74	77.493324	127.0.0.1	127.0.0.1	AMQP	80	Queue.Declare q=test 
```

This leads me to conclude that RabbitMQ does honour nowait (at least for queues, but I suspect exchanges are the same).

**Comment by cressie176** [comment]
Thinking abut nowait some more, I'm curious as to its utility. Instructing the broker to create a queue or exchange, but not waiting for it to be created seems dangerous given that any attempt to use them prematurely will break the channel. So while nowait is part of the amqp 0.9.1 spec and appears to be supported by RabbitMQ, implementing it in amqplib could cause more harm than good.

**Comment by KristjanTammekivi** [comment]
Hmm back in 2020 I answered with the confidence of a man that had seen somewhere in the docs that rabbitmq ignores that bit. Can't find it anymore and You've proven it to not ignore it.

Anyway, I think it's best to add people the option and if they misuse it it's not your fault.

**Comment by cressie176** [comment]
I'm still getting familiar with the amqplib internals, but I think the way to implement this would be to check for the presence of a `nowait` option and use sendImmediately rather than rpc, as there would be no reply. I don't believe sendImmediately returns a promise though which could end up calling a lot of confusion. Before going any further I'll post something to the RabbitMQ mailing list and see if they have any suggestions for whether it's worth implementing `nowait` I'm struggling to think of a use case where it would be so important to create queues/exchanges without waiting.

**Comment by cressie176** [comment]
Michael from the RabbitMQ team confirmed that the only practical use for the `nowait` option is if you are creating or binding large numbers of queues / exchanges and don't care about the result. I'm going to close as the original issue is from 2019. If someone requests it we can always re-open.
