### ISSUE TITLE
AssertionError: this.newStreams.length != 0

### ISSUE THREAD

**Issue by jwalton** [amqp-node/amqplib#546]
In the past couple of weeks, I've started seeing this assert:

https://github.com/squaremo/amqp.node/blob/v0.5.5/lib/mux.js#L92

being raised on my production servers a few times a day.  Whenever it's raised, `this.newStreams.length` is always 28:

```
AssertionError [ERR_ASSERTION]: 0 == 28

at Mux._readIncoming (./node_modules/amqplib/lib/mux.js:92:12)
at Immediate._onImmediate (./node_modules/amqplib/lib/mux.js:112:12)
at processImmediate (internal/timers.js:439:21)
```

**Comment by squaremo** [comment]
I think this assertion firing was the motivation behind #503. Do you have the capacity to try `master`?

**Comment by squaremo** [comment]
> Do you have the capacity to try `master`?

Ah, production server, probably not. Maybe you could try to produce the problem locally. But failing that, I should do a release soon.

**Comment by jwalton** [comment]
I'm adventurous, and it looks like a simple enough change.  I can try this on master for a day.  :)

**Comment by jwalton** [comment]
Hmm... I tried adding:

```
    "amqplib": "git://github.com/squaremo/amqp.node.git#90e0dc081b0f57aa6eff4e24ae3f56da12aa57eb",
```

to my package.json, but I'm getting this error:

```
Error: Cannot find module './defs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/runner/work/loop/loop/node_modules/amqplib/lib/connection.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

I'm guessing this is something generated?  Any easy way to run master?  :P

**Comment by cressie176** [comment]
Hi @jwalton,

It think you'll need to run [prepare](https://github.com/squaremo/amqp.node/blob/master/package.json#L30) to generate the defs. I suspect it hasn't worked due to the git dependency, although the the [docs](https://docs.npmjs.com/misc/scripts) imply otherwise...

> prepare: Run both BEFORE the package is packed and published, on local npm install without any arguments, and when installing git dependencies (See below). This is run AFTER prepublish, but BEFORE prepublishOnly.

You might find running `npm install` locally with no arguments does the trick too.

**Comment by jwalton** [comment]
Ok, I took a little hackery to get my ci pipeline to run `npm prepare` (if you run `npm prune --production` npm overwrites the amqplib package, so I have to run it quite late in my Dockerfile, and at that point I'm in an image without `make` or `curl` -_-), but I got it going.  I also realized this was failing quite a bit on my staging environment, too, so I don't even have to push this to production.  :)

**Comment by jwalton** [comment]
This does seem to have fixed the assert issue for me in my staging environment (one of my processes was restarting about 5 times an hour, and it hasn't restarted at all since I upgrade amqplib to master).  I guess we need a new release @squaremo.  :D

**Comment by cressie176** [comment]
Believe the fix was released.
