### ISSUE TITLE
Update NPM version

### ISSUE THREAD

**Issue by Kasea** [amqp-node/amqplib#551]
Would it be possible to update the NPM entry for this library? The NPM version has a bug which is fixed on live version. The bug is seen below, don't want to use github link in my package.json in prod.

OS: Mac (not sure how to check version tbh)
Node: 12.9.1

```
assert.js:89
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: 0 == 1
    at Mux._readIncoming (/Users/tarzan/Documents/<package name>/node_modules/amqplib/lib/mux.js:92:12)
    at Immediate._onImmediate (/Users/tarzan/Documents/<package name>/node_modules/amqplib/lib/mux.js:112:12)
    at processImmediate (internal/timers.js:439:21) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 0,
  expected: 1,
  operator: '=='
}
```

**Comment by johanneswuerbach** [comment]
@squaremo any chance you could release the latest master? Would really much appreciate it 😍

**Comment by johanneswuerbach** [comment]
@squaremo looks like you created a new tag https://github.com/squaremo/amqp.node/releases/tag/v0.5.6, but there is no new version published yet https://www.npmjs.com/package/amqplib

**Comment by squaremo** [comment]
Yeah, I tagged it for release, forgot I needed to change the package.json
for the automation to publish it, then bumped up against working hours. New
version published just now.

**Comment by Uzlopak** [comment]
This issue should be closed
