### ISSUE TITLE
Update tutorials Readme to point to Javascript code examples instead of Python

### ISSUE THREAD

**Issue by amirsaleem-kn** [amqp-node/amqplib#553]
Current tutorial examples redirect to Python code examples. RabbitMq now has a javascript code sample which will be much easier for the JS developers to understand the implementation. I have cloned the repository and updated the Readme. Add me as a contributor so that I can push my branch to the origin.

Thanks

**Comment by KristjanTammekivi** [comment]
Easier to just create a PR

**Comment by cressie176** [comment]
I've updated the tutorial readme
