### ISSUE TITLE
Documentation: how to properly use a Connection object

### ISSUE THREAD

**Issue by raijinsetsu** [amqp-node/amqplib#587]
Reading through the documentation, it's not clear whether a connection can be used for multiple channels are not. For example:
```typescript
const conn = await connect({});
const chan1 = await conn.createChannel(); // used by one section of the logic
const chan2 = await conn.createChannel(); // used by another section of the logic
```
vs.
```typescript
const chan1 = (await connect({})).createChannel();
const chan2 = (await connect({})).createChannel();
```

Based SOLELY on how errors at the channel level close the connection, my assumption is that it SHOULD be implemented as the latter option. I have not fully tested out either situation.

**Comment by cressie176** [comment]
A single connection can, and usually should be used to create multiple channels. That's kind of the point of them - a connection takes longer and more resources to establish. I don't believe that errors at a channel kill the connection (unless they aren't handled). However the reverse is true - a connection error will naturally kill the channel.
