### ISSUE TITLE
heartbeat feature implements wrongly

### ISSUE THREAD

**Issue by zyf0330** [amqp-node/amqplib#588]
Accorgind to https://www.rabbitmq.com/heartbeats.html, heartbeat frame should be sent every `timeout/2` seconds, and default timeout value is 60 from rabbitmq server. But amqplib treats it as interval value and causing that heartbeat frame is sent every `timeout` seconds which is 60s but should be 30s.

Another problem is, rabbitmq-heartbeats doc above says that connection should be considered to be unreachable after two missed heartbeat frame. But according to logic implemented by amqplib now, `timeout` is emitted on connection after twice `interval` value which is default 120s but should be 60s.

**Comment by squaremo** [comment]
I think you're basing this analysis on these sentences in the linked doc:

> Heartbeat frames are sent about every heartbeat timeout / 2 seconds. This value is sometimes referred to as the heartbeat interval. After two missed heartbeats, the peer is considered to be unreachable.

You can read that as meaning that a peer is considered unreachable after `2 * timeout/2`, but this is not the case. https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_heartbeat.erl#L80 shows that the threshold is two heartbeat _timeouts_ (although the comment mentions intervals, it's just using that word in the generic sense).

The timeout is given in https://github.com/rabbitmq/rabbitmq-server/blob/58a3b450ab3cabe29576bfb6504449c94ae1ac62/src/rabbit_reader.erl#L1210, and you can see it's just the value negotiated with the client.

> But amqplib treats [the timeout] as interval value and causing that heartbeat frame is sent every timeout seconds which is 60s but should be 30s.

https://github.com/squaremo/amqp.node/blob/master/lib/heartbeat.js#L65 shows the check for sending a heartbeat is run every `timeout/2`.

If there's a subtlety in the code that I'm missing, you'll need to explain it to me :-)

**Comment by zyf0330** [comment]
Though https://github.com/squaremo/amqp.node/blob/master/lib/heartbeat.js#L65 shows `setInterval` uses `timeout/2` as timer interval, but `checkSend` causes that a heartbeat frame is sent every two loop actually, because sending heartbeat frame makes `checkSend` return true. Am I wrong?

**Comment by squaremo** [comment]
Let's see -- with timeout=1.0, assuming a frame has just been sent, and no other frames are sent, the order of calls would be:

```
t=0 interval timer fires
checkSend returns true and sets sentSinceLastCheck to false
(no heartbeat sent, since true)

t=0.5 interval timer fires
checkSend returns false and sets sentSinceLastCheck to false
heartbeat sent, setting sentSinceLastCheck to true

t=1.0 interval timer fires
checkSend returns true and sets sentSinceLastCheck to false
(no heartbeat sent, since true)

t=1.5 interval timer fires
checkSend returns false and sets sentSinceLastCheck to false
heartbeat sent, setting sentSinceLastCheck to true
```

.. and so on. Heartbeats are sent at 0.5 and 1.5, i.e., one timeout apart. I think you are correct that the result is a heartbeat is sent (assuming no other frames) every `timeout`, rather than every `timeout / 2`.

Carefully reading https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_heartbeat.erl#L73 and what follows -- wow, that is tortuous, I do not miss having to read Erlang code -- it resets its equivalent of `sentSinceLastCheck` _after_ it has sent a heartbeat. The key bit is https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_heartbeat.erl#L163, which checks the socket stats again after running `Handler`, which in the heartbeat sender case is what sends a heartbeat frame on the socket. It looks like this was a change made a couple of years ago: https://github.com/rabbitmq/rabbitmq-common/commit/b76227e22da22a85a8ff4ee96efde409a89a1992.

So the implementation here, and that in rabbitmq-common, now differ. I'm not sure the difference matters, though. The AMQP 0-9-1 specification says:

> If a peer detects no incoming traffic (i.e. received octets) for two heartbeat intervals or longer, it should close the connection without following the Connection.Close/Close-Ok handshaking, and log an error.

(where "interval" refers to the negotiated heartbeat timeout). How often a heartbeat is _actually sent_ is left to the implementation -- to avoid being considered dead, you need to ensure some bytes are read at the other side at least every `timeout * 2`. Sending every `timeout` is probably good enough when `timeout` is way larger than the latency on the connection. Sending every `timeout / 2` is being overly cautious, in my opinion. I'm not sure how the RabbitMQ developers convinced themselves it was necessary, but if you want to try and figure that out for yourself, it appears to have happened here: https://groups.google.com/g/rabbitmq-users/c/djNpSuQoznY/discussion.

**Comment by zyf0330** [comment]
About this in doc
> If a peer detects no incoming traffic (i.e. received octets) for two heartbeat intervals or longer, it should close the connection without following the Connection.Close/Close-Ok handshaking, and log an error.

you said
> (where "interval" refers to the negotiated heartbeat timeout). 

I have different opinion, I think this interval is actually **interval of sending heartbeat frame** which is `timeout/2`.

Because this sentence in doc before that sentence
> The peer should make a best effort to send heartbeats at specified `intervals`

And you have admitted this interval is `timeout/2`

These are my understandings.

**Comment by squaremo** [comment]
Those sentences appear in the AMQP 0.9.1 specification https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf, which does not define "interval" (as `timeout / 2` or in any other terms). It's just "interval" in the generic sense of "a period of time". The specification precedes RabbitMQ documentation, so definitions in the latter do not apply in the specification.

**Comment by zyf0330** [comment]
Yes.
So we two agree that, in both AMQP 0.9.1 specification and Rabbitmq doc, connection should be closed after two heartbeat intervals, which means if we name **interval of sending heartbeat frame** `interval`, and name **elapsed time to consider connection to be unreachable** `timeout`, then we get that value of interval equals value of timeout / 2.
The actual behavior in amqp.node is the same with above logic. But exactly, it is a mistaken implementation which does just right thing. So I think this part needs to be improved.
As for timeout is 30 or 60, I think the point is amqp.node actually treats `timeout` as `interval` coming from rabbitmq server.

**Comment by squaremo** [comment]
No, I don't agree with that. The specification does not support that interpretation. There is one setting -- the heartbeat timeout, in seconds. The specification says that if you have not received anything from a peer for twice that number of seconds, you should consider that connection dead. That's all.

The reason it says _two_ heartbeats is to avoid aliasing. Say it were _one_ heartbeat, and you're connected to a peer that sends a heartbeat on exactly the right schedule -- one every heartbeat timeout. You check just _after_ getting a heartbeat frame, but for the next check, the frame is delayed by \epsilon (a small length of time), and you don't see it -- now you have to cut the connection, even though the peer is doing what's expected. Waiting for twice the length of time means that (provided \epsilon is much smaller than the heartbeat timeout) you are very unlikely to falsely detect a dead connection.

Dividing the timeout by two for sending heartbeats works on a similar idea. Say you checked whether you'd sent anything only every timeout. If you check, then send immediately afterwards, you next check will very likely indicate you don't need to send a heartbeat. You'll only notice you haven't sent anything at the _next_ check, which is almost twice the heartbeat timeout later, so if your heartbeat frame is delayed, the connection might be deemed dead.

Note that it's only _checking_ that you need to do at twice the rate. You're still aiming to _send_ once every timeout seconds.

**Comment by zyf0330** [comment]
Firstly, the timeout after how long to cut connection that I mentioned above is a lower limit. When thinking about checking interval jitter or some other things, exact time range to cut connection may be 1-1.5 * timeout. I agree your words about this.
Finally, my only problem is, in Rabbitmq doc it says 
> Heartbeat frames are sent about every `heartbeat timeout / 2` seconds.

And it gives default value

> The value is in seconds, and default value suggested by RabbitMQ is 60.

Rabbitmq server passes this value 60 which it treats it as `heartbeat timeout`, but amqp.node receives it from server and treats it as `heartbeat interval` and causes that headrbeat frames are sent every `heartbeat timeout` seconds.This causes that client and server have different definition of `heartbeat timeout` between each other. 
In reality, I make this mistake too. After I saw Rabbitmq doc, I think this `timeout` option value is the lowest limit to detect a connection unreachable, but in amqp.node the lowest limit is actually `2 * timeout`.

Sorry, My English capability is poor and not sure if you understand me.

**Comment by cressie176** [comment]
> Sending every timeout / 2 is being overly cautious, in my opinion. I'm not sure how the RabbitMQ developers convinced themselves it was necessary, 

With a timeout of 60 seconds and the server dropping connections if it doesn't receive a heartbeat within 120s, I can imagine the following scenario...

| Heartbeat | Sent | Outcome |
|----|----|----|
| 1 | 60s | Reached the server |
| 2 | 120s | Lost somehow |
| 3 | 180s | Reached the server 120.1s after heartbeat 1, causing the server to drop the connection |

Unless I've misunderstood something?

**Comment by cressie176** [comment]
I tested the above scenario using the following script and by [hacking amqplib to suppress the heartbeat](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L515), and it's not what I feared. 

```js
const amqplib = require('amqplib');

(async () => {
  const connection = await amqplib.connect('amqp://localhost:5672?heartbeat=10')
  const connected = new Date();
  console.log('Connected:   ', connected);
  connection.on('error', () => {
    const disconnected = new Date();
    console.log('Disconnected:', disconnected);
    console.log('Timeout:     ', Math.floor((disconnected.getTime() - connected.getTime()) / 1000));
  });
})();
```
### Output
```
Connected:    2022-05-15T10:12:06.142Z
Disconnected: 2022-05-15T10:12:35.825Z
Timeout:      29
```
I reran using a heartbeat of 30s and 60s and the timeouts occurred at 89s and 178s respectively, leaving plenty of time for a heartbeat to arrive in the event that one is dropped. 

Therefore I'm closing this issue as the current heartbeat implementation appears sound.
