### ISSUE TITLE
Url with empty vhost name still connect to vhost "/"

### ISSUE THREAD

**Issue by zyf0330** [amqp-node/amqplib#589]
I pass url `amqp://localhost/` to amqplib to connect to rabbitmq, but it still connects to vhost "/".

**Comment by zyf0330** [comment]
I check vhost here.
![image](https://user-images.githubusercontent.com/11958657/95643994-becfa580-0ae5-11eb-9272-35a891ec2b79.png)

**Comment by zyf0330** [comment]
And I noticed that url `amqp://localhost//vhost` can connect to vhost `/vhost`. But according to spec, the url should be `amqp://localhost/%2fvhost`. Of course, the latter url connects to vhost `/vhost` successfully too.

**Comment by cressie176** [comment]
Agree there's a spec violation here. From the [uri documentation](https://www.rabbitmq.com/uri-spec.html)

```
amqp_URI       = "amqp://" amqp_authority [ "/" vhost ] [ "?" query ]
amqp_authority = [ amqp_userinfo "@" ] host [ ":" port ]
amqp_userinfo  = username [ ":" password ]
username       = *( unreserved / pct-encoded / sub-delims )
password       = *( unreserved / pct-encoded / sub-delims )
vhost          = segment
```

> The vhost component may be absent; this is indicated by the lack of a "/" character following the amqp_authority. An absent vhost component is not equivalent to an empty (i.e. zero-length) vhost name.
>
> Certain URI components (the port, username, password, vhost and query) may be absent from a URI. The host may not be absent, but may be zero-length; for the purposes of this section, a zero-length host is treated as absent.
>
> Apart from the port (which is covered in the section 2.2 above), this specification does not mandate how implementations should handle absent components. Possible approaches include, but are not limited to, the following:
> 
> * An absent component may be substituted with a default value.

So it is OK for amplib to default the vhost to '/' when absent, but the vhost name should be a zero length string when the vhost segment is just `/`

```javascript
const amqp = require('amqplib');

(async () => {
  await connect('amqp://localhost:5672/vhost', 'vhost');
  await connect('amqp://localhost:5672/v%2fhost', 'v/host');
  await connect('amqp://', '/');
  await connect('amqp://:@/', '');
  await connect('amqp://user@', '/');
  await connect('amqp://user:pass@', '/');
  await connect('amqp://localhost', '/');
  await connect('amqp://:5672', '/');
  await connect('amqp:///vhost', 'vhost');
  await connect('amqp://host/', '');
  await connect('amqp://host/%2f', '/');
})();

async function connect(url, expected) {
  process.once('vhost', ({ url, vhost }) => {
    console.log('|', url, '|', vhost, '|', expected, '|', expected === vhost ? 'OK' : 'NOT OK', '|')
  })
  try {
    const connection = await amqp.connect(url)
    await connection.close();
  } catch(error) {
    //ok
  }
}
```

| URL | Actual vhost | Expected vhost | Result |
|----|----|----|----|
| amqp://localhost:5672/vhost | vhost | vhost | OK |
| amqp://localhost:5672/v%2fhost | v/host | v/host | OK |
| amqp:// | / | / | OK |
| amqp://:@/ | / |  | NOT OK |
| amqp://user@ | / | / | OK |
| amqp://user:pass@ | / | / | OK |
| amqp://localhost | / | / | OK |
| amqp://:5672 | / | / | OK |
| amqp:///vhost | vhost | vhost | OK |
| amqp://localhost/ | / |  | NOT OK |
| amqp://localhost/%2f | / | / | OK |

**Comment by cressie176** [comment]
I tried connecting using a connection object specifying `{ vhost: '' }` instead of the uri, but it was still set to `/` due to [this](https://github.com/amqp-node/amqplib/blob/main/lib/connect.js#L47-L48) line.

**Comment by cressie176** [comment]
Creating via the HTTP API fails too

```
curl -vvv -X PUT 'http://guest:guest@localhost:15672/api/vhosts/'

< HTTP/1.1 405 Method Not Allowed
< allow: HEAD, GET, OPTIONS
< content-length: 0
< content-security-policy: script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'self'
< date: Fri, 06 May 2022 07:32:28 GMT
< server: Cowboy
< vary: origin
```

I think it's safe to ignore this issue as I can't find a way to create a vhost without a name.

>
