### ISSUE TITLE
messageTtl in String

### ISSUE THREAD

**Issue by clarkttfu** [amqp-node/amqplib#591]
Hi there, 

It will be great that amqplib could automatically convert the value in String into Number.

Clark

https://www.squaremobius.net/amqp.node/channel_api.html#channel_assertQueue
> messageTtl (0 <= n < 2^32): expires messages arriving in the queue after n milliseconds

**Comment by cressie176** [comment]
Doesn't look too difficult [messageTtl](https://github.com/amqp-node/amqplib/blob/243aef8b6da766a3b9908bc50b2be4859eef43a6/lib/api_args.js#L53-L62) and friends could be adapted to use a new `setNumberIfDefined()` function that did the conversion if a value was present.

However, what would worry me is the inconsistent behaviour from any other `x-` arguments that aren't listed in these options and that take numeric values. I would therefore prefer to leave things as they are.

**Comment by cressie176** [comment]
Closing, but happy to reconsider  if there are good grounds to do so
