### ISSUE TITLE
npm audit is reporting a high severity issue for amqplib dependency

### ISSUE THREAD

**Issue by ogradyt** [amqp-node/amqplib#625]
amqplib is dependent on url-parse, which has a high vulnerability in it.

https://www.npmjs.com/advisories/1678

![image](https://user-images.githubusercontent.com/36517650/117380879-f7770800-ae97-11eb-8e85-e6dad04158e0.png)

**Comment by rprakash05** [comment]
Updating amqlib to the current version should fix the issue  i.e npm install amqplib@0.7.1.  The current version of amqlib uses the version of url-parse that  has patched the vulnerability

**Comment by Vilya2** [comment]
Having amqplib in 0.7.1 and still have this vulnerability ...

**Comment by cressie176** [comment]
Duplicate of https://github.com/amqp-node/amqplib/issues/677
