### ISSUE TITLE
Replace Bluebird with native promises

### ISSUE THREAD

**Issue by kibertoad** [amqp-node/amqplib#627]
As Matteo Collina once said, "The first rule of Node.js performance optimization is to remove bluebird" (https://twitter.com/matteocollina/status/1351949461371686914)

Considering that support for older Node versions was dropped, it should be fairly straightforward to adjust current implementation to fully utilize native promises instead.

If there is approval for this change, I can provide a PR implementing it.

**Comment by jimmywarting** [comment]
👍 
Drop support for older node version, safe-buffer can be replaced with buffer from node

**Comment by kibertoad** [comment]
PR for this was already up: https://github.com/squaremo/amqp.node/pull/624

**Comment by kpkonghk01** [comment]
Any update on this topic?

**Comment by carlhoerberg** [comment]
https://github.com/cloudamqp/amqp-client.js/ is a newer AMQP library that uses native promises (along with other improvements)

**Comment by cressie176** [comment]
amqplib@0.10.0 uses native promises
