### ISSUE TITLE
Why did I use this sentence to close the connection, but did not close the heartbeat timer, resulting in a heartbeat timeout error

### ISSUE THREAD

**Issue by mytwz** [amqp-node/amqplib#640]
### I hope the author can help me answer

let __mqconnect = await connect(this.uri);
....
### **Why did I use this sentence to close the connection, but did not close the heartbeat timer, resulting in a heartbeat timeout error**

__mqconnect.close();
0|IM1  | Error: Heartbeat timeout
0|IM1  |     at Heart.<anonymous> (/data/Livenew/node_modules/socket.io-amqplib/node_modules/amqplib/lib/connection.js:427:19)
0|IM1  |     at Heart.emit (events.js:315:20)
0|IM1  |     at Heart.runHeartbeat (/data/Livenew/node_modules/socket.io-amqplib/node_modules/amqplib/lib/heartbeat.js:88:17)
0|IM1  |     at listOnTimeout (internal/timers.js:549:17)
0|IM1  |     at processTimers (internal/timers.js:492:7)

### **// I checked the source code
// I checked a lot of documents combined with this part of the source code, but I still can't find the reason**
// A close has been confirmed. Cease all communication.
C.toClosed = function(capturedStack, maybeErr) {
    this._closeChannels(capturedStack);
    var info = fmt('Connection closed (%s)',
                    (maybeErr) ? maybeErr.toString() : 'by client');
    // Tidy up, invalidate enverything, dynamite the bridges.
    invalidateSend(this, info, capturedStack);
    this.accept = invalidOp(info, capturedStack);
    this.close = function(cb) {
        ### **// I began to think that it might be because of this: the exception of sending a message during the shutdown caused the shutdown interrupt to not turn off the timer, but I checked the log and found no such error**
        cb && cb(new IllegalOperationError(info, capturedStack));
    };
    if (this.heartbeater) this.heartbeater.clear();
    // This is certainly true now, if it wasn't before
    this.expectSocketClose = true;
    this.stream.end();
    this.emit('close', maybeErr);
};

**Comment by cressie176** [comment]
I've tested with the following script and the wireshark debug clearly shows the heartbeats stop when close is call

```javascript
const amqplib = require('amqplib');

(async () => {
  const connection = await amqplib.connect('amqp://localhost?heartbeat=1');
  setTimeout(async () => {
    await connection.close();
  }, 5000)
})();

setInterval(() => {}, 100000)
```

```
18	9.338772	127.0.0.1	127.0.0.1	AMQP	570	Connection.Start 
20	9.341258	127.0.0.1	127.0.0.1	AMQP	378	Connection.Start-Ok 
22	9.342241	127.0.0.1	127.0.0.1	AMQP	76	Connection.Tune 
24	9.342663	127.0.0.1	127.0.0.1	AMQP	76	Connection.Tune-Ok 
26	9.342786	127.0.0.1	127.0.0.1	AMQP	72	Connection.Open vhost=/ 
28	9.343728	127.0.0.1	127.0.0.1	AMQP	69	Connection.Open-Ok 
30	9.844837	127.0.0.1	127.0.0.1	AMQP	64	Heartbeat 
32	10.346213	127.0.0.1	127.0.0.1	AMQP	64	Heartbeat 
34	10.346679	127.0.0.1	127.0.0.1	AMQP	64	Heartbeat 
36	10.851662	127.0.0.1	127.0.0.1	AMQP	64	Heartbeat 
38	11.347743	127.0.0.1	127.0.0.1	AMQP	64	Heartbeat 
40	11.356916	127.0.0.1	127.0.0.1	AMQP	64	Heartbeat 
42	11.863003	127.0.0.1	127.0.0.1	AMQP	64	Heartbeat 
44	12.353574	127.0.0.1	127.0.0.1	AMQP	64	Heartbeat 
46	12.369096	127.0.0.1	127.0.0.1	AMQP	64	Heartbeat 
48	12.874052	127.0.0.1	127.0.0.1	AMQP	64	Heartbeat 
50	13.356708	127.0.0.1	127.0.0.1	AMQP	64	Heartbeat 
52	13.379982	127.0.0.1	127.0.0.1	AMQP	64	Heartbeat 
54	13.884285	127.0.0.1	127.0.0.1	AMQP	64	Heartbeat 
56	14.349523	127.0.0.1	127.0.0.1	AMQP	89	Connection.Close reply=Cheers, thanks 
58	14.350831	127.0.0.1	127.0.0.1	AMQP	68	Connection.Close-Ok 
```
I left the application running for a few minutes after closing the connection without issue. If you paste your code (preferably in a snippet like the above) I can take a look. Also I suggest you try using [wireshark](https://www.rabbitmq.com/amqp-wireshark.html) to see the interaction between your client and server.

**Comment by cressie176** [comment]
I've walked through the code and the only potential for not stopping the heartbeats I can is if the client [sent a ConnectionClose](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L342-L346) to the server but never [received a ConnectionCloseOK reply](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L385-L389) and so [never cleared the heartbeat](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L418). If this was the case then it is actually correct for you to receive a heartbeat timeout. I'll see if I can reproduce.

**Comment by cressie176** [comment]
If I return early from [accept method](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L386) in Connection.toClosing, simulating never receiving a connection close, I can reproduce. It's likely then your application never received the Connection.Close-OK operation from the broker and so continued to heartbeat.
