### ISSUE TITLE
url-parse module contains security vulnerability

### ISSUE THREAD

**Issue by barakSpoj** [amqp-node/amqplib#642]
Please update this module to >=1.5.2, its failing our auditing
Thanks!

**Comment by kibertoad** [comment]
wonder if it could be replaced by native url parsing

**Comment by jimmywarting** [comment]
+1 for `new URL(str)`

**Comment by sukusukumar** [comment]
I see that url-parse is migrated to latest version in packag.json. Can this change be published to npm, please?

**Comment by carlhoerberg** [comment]
You can pull the dependency straight from github: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#github-url

**Comment by cressie176** [comment]
Duplicate of https://github.com/amqp-node/amqplib/issues/677
