### ISSUE TITLE
Connection closed when no `error` listeners on channel

### ISSUE THREAD

**Issue by muter** [amqp-node/amqplib#649]
Any channel closed by server, (i.e. in case of failed _rpc call) is leading to a whole connection being closed, if 'error' event handler is not attached to that channel. This is unexpected, since [AMQP invalidates only one channel][1] when facing recoverable error, such as 404 on `checkQueue` calls.

Code snippet to reproduce the behavior:
```js
const amqplib = require("amqplib");

async function checkNonexistentQueue() {
  const connection = await amqplib.connect({ hostname: "message-broker", username: "guest", password: "guest" });
  connection.addListener("close", e => console.error("[__Connection closed__]", e.message));
  connection.addListener("error", e => console.error("[Connection error]", e.message));
  const channel = await connection.createConfirmChannel();
  channel.checkQueue("nonexiststent").catch(e => console.error("[Check failed]", e.message));
}

void checkNonexistentQueue();
```

Running this produces the following output:
>[Connection error] Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'nonexiststent' in vhost '/'"
>[__Connection closed__] Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'nonexiststent' in vhost '/'"
>[Check failed] Operation failed: QueueDeclare; 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'nonexiststent' in vhost '/'"

[Errors are special case in node event emitters][2]. Since Channel is an event emitter, call to `this.emit('error', err)` while processing `ChannelClose` in [channel.js](../blob/main/lib/channel.js#L425) throws an error. This error is caught in `acceptLoop` in [connection.js](../blob/main/lib/connection.js#L480) and is treated as a `frameError`, leading to connection being abruptly closed.

As far I can see this behavior is not documented anywhere. 

Perhaps unhandled channel close errors should not cause a connection being closed, but rather should be processed as a separate connection-wide error, such as `unhandledChannelError`, or even ignored entirely. I hope for some discussion here.

Thank you.

[1]: https://www.rabbitmq.com/channels.html#error-handling
[2]: https://nodejs.org/docs/latest/api/events.html#events_error_events

**Comment by cressie176** [comment]
Hi @muter,

I agree that it is undesirable for a channel error to break the connection, although not sure how feasible it is to resolve while still emitting an error event from the channel. I suspect it's far too late to change this behaviour, since a large number of applications have already been written to expect this.

The workaround is for the application to register 'error' and 'close' listeners, then to handle accordingly (e.g. by creating a new channel and consuming again).

**Comment by muter** [comment]
Hi @cressie176,

I can agree with your point. Change to the current behavior would break some software for sure. But I'm not entirely comfortable with connection being closed abruptly, without proper server notification. 

And, I think, some mention of this behavior in the docs would be necessary.

**Comment by cressie176** [comment]
I've added a [note](https://github.com/amqp-node/amqplib/commit/b1c4029b5a418a16b8fdacb7bbdb8484f2e1c744) to the channel api documentation.
