### ISSUE TITLE
Are there any plans to support the new streams protocol released by RabbitMQ?

### ISSUE THREAD

**Issue by alilland** [amqp-node/amqplib#664]
It looks like RabbitMQ has released a feature this year allowing users to create streams with RabbitMQ

https://www.rabbitmq.com/stream.html

Default clients running amqp can still use the new feature, but it wont get most of the benefits of the new protocol

I posted the same question on the main RabbitMQ for ruby client here - they answered that they do not plan to support it and that it would require a new client
https://github.com/ruby-amqp/bunny/issues/623

Does amqp.node plan to support this new protocol?

At this time it looks like no programming languages support the new features except for Java and Go

**Comment by squaremo** [comment]
Hmm, yeah that's a completely disjoint protocol. To the extent that this library is an AMQP 0-9-1 client library, it's out of scope; and to the extent that this library is de facto a _RabbitMQ_ client library, it would be a nice addition to support the streams protocol, though it wouldn't share much if any of the existing code. Speaking for myself, it's unlikely I would have time to implement the streams protocol, or review someone else's work, even if I think it would be fun to do so :-)

**Comment by carlhoerberg** [comment]
You can still access and use Stream queues with this (or any amqp) library, just set the correct queue type when declaring the queue.
