### ISSUE TITLE
Connection.Tune-Ok channel-max defaults to 0, potential spec violation

### ISSUE THREAD

**Issue by Nilstrieb** [amqp-node/amqplib#672]
When tuning the connection, `amqplib` defaults the `channel-max` to 0.
But in the [spec](https://www.rabbitmq.com/resources/specs/amqp0-9-1.xml), it states that that number must be "notnull". I'm currently implementing my own broker, and encountered this problem when testing it using `amqplib`.

My broker proposes `0`, and then amqplib responds with 0. 

*Although the spec doesn't make much sense here, since it also says that the `Tune-Ok.channel-max` must be less or equal than `Tune.channel-max`, which is allowed to be 0, but I'd like to hear your opinion on this anyways.*

I've also tried it with the python pika client, which just sends `65536`.

Am I understanding something wrong, or is there an issue here?

```xml
<!-- Snipped from the spec -->
<field name="channel-max" domain="short" label="negotiated maximum channels">
  <doc> The maximum total number of channels that the client will use per connection. </doc>
    <rule name="upper-limit">
    <doc> If the client specifies a channel max that is higher than the value provided by the server, the server MUST close the connection without attempting a negotiated close. The server may report the error in some fashion to assist implementors. </doc>
  </rule>
  <assert check="notnull"/>
  <assert check="le" method="tune" field="channel-max"/>
</field>
```

**Comment by cressie176** [comment]
The RabbitMQ [xml spec](https://www.rabbitmq.com/resources/specs/amqp0-9-1.xml) says zero is allowed - it means just use the server setting.  There's some more info in the [errata](https://www.rabbitmq.com/amqp-0-9-1-errata.html#section_10).

**Comment by Nilstrieb** [comment]
Ah, didn't read the errata. RabbitMQs interpretation makes sense, I'll close the issue. I guess it really is ambiguous :D
