### ISSUE TITLE
Security vulnerability in url-parse, please update module to version >=1.5.8

### ISSUE THREAD

**Issue by nicholeuf** [amqp-node/amqplib#677]
https://github.com/advisories/GHSA-hgjh-723h-mx2j

**Comment by nicholeuf** [comment]
I see there's been a merged fix https://github.com/amqp-node/amqplib/pull/675 but it's not yet released.

**Comment by GianFF** [comment]
any update on this? I'm having issues because of this nested-dependency vulnerability.

**Comment by cressie176** [comment]
Fixed in amqplib-0.9.0
