### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by MichaelTurbe** [amqp-node/amqplib#679]
With open vulnerabilities and open pull requests it appears that this project is abandoned. Can anyone please confirm if there are contributors willing to pull in the PRs that could make the project secure again?
Thanks

**Comment by kibertoad** [comment]
I'm happy to review urgent outstanding PRs if you believe there are any, but I need @squaremo help to publish new version on npm.

**Comment by MichaelTurbe** [comment]
Since NPM started putting security vulnerability advisories into installations many organizations have developed policies against libraries with open vulnerabilities, and the security vulnerability in url-parse is a major issue in that regard.  Essentially, many folks using node cannot even initiate new RabbitMQ projects because of it.  Would be greatly, greatly appreciated if a new build could be published.  Thanks for responding!

**Comment by carlhoerberg** [comment]
I recommend you to take a look at https://github.com/cloudamqp/amqp-client.js 
A 0-dependency JS client, fully support by CloudAMQP (largest RabbitMQ hosting provider)
