### ISSUE TITLE
Do not copy hostname to socket options servername (server name indication)

### ISSUE THREAD

**Issue by urbanhusky** [amqp-node/amqplib#697]
RFC 6066 specifies that the Server Name Indication must not be an IP address.
Unfortunately amqplib blindly copies the hostname from the url to this field, which causes DEP0123 warnings when connecting to an IP address. 
Besides, the hostname is not necessarily identical to the server name indication, so it should be configurable e.g. via the `socketOptions` provided to `connect(…)`

Source:
https://github.com/amqp-node/amqplib/blob/main/lib/connect.js#L109  
https://datatracker.ietf.org/doc/html/rfc6066#section-3

**Comment by cressie176** [comment]
Hi @urbanhusky,
Thanks for reporting. I agree.

**Comment by cressie176** [comment]
Published as amqplib@0.10.1
