### ISSUE TITLE
Question mark in password breaks connection string

### ISSUE THREAD

**Issue by aleybovich** [amqp-node/amqplib#700]
When executing this line:

    const conn = await amqp.connect(`amqp://${user}:${pass}@${host}:${port}`);

if `pass` contains a `?` (e.g. `abc?def`) then only the part of the password before `?` is being used, leading to authentication errors. 

Any workaround?

**Comment by cressie176** [comment]
Have you tried escaping it?

**Comment by cressie176** [comment]
```
  const connection = await amqplib.connect('amqp://steve:pass%3Fword@localhost');
```
works for me
