### ISSUE TITLE
Channel connection status

### ISSUE THREAD

**Issue by amitagarwal-dev** [amqp-node/amqplib#703]
Hi,
Is there any way to get the channel or rabbitmq connection status?  
Something like:  
```js  
mqconn.isConnected  
chconn.isConnected

**Comment by amitagarwal-dev** [comment]
@cressie176

**Comment by cressie176** [comment]
Not that I'm aware of. Best thing is to listen for the connection close / error events and respond accordingly

**Comment by amitagarwal-dev** [comment]
Is there any chance of adding this in future?  
I thought of checking this flag before publishing in order to prevent message loss when rabbitmq is down.

**Comment by cressie176** [comment]
> Is there any chance of adding this in future?

No, it would duplicate something that's already possible but in a less flexible way. For example, some people may prefer to respond to these events once, when they happen as opposed to whenever you want to publish a message. You might for example, want to reconnect to a different broker instance. For this an event based API is more appropriate

This isn't to say that your idea isn't also appropriate, but (a) it can be achieved with the existing events api, and (b) you need to consider more than just whether the connection is open. You also need to consider whether the connection is [blocked](https://www.rabbitmq.com/connection-blocked.html), whether the channel is open and potentially whether the channel is saturated.

I created an example for how you might do this [here](https://github.com/cressie176/amqplib-express-example/blob/4008d2720182cefdb84c3e1a8af5f5dcd6650882/lib/middleware.js#L18-L24), although it doesn't handle blocked connections.

**Comment by cressie176** [comment]
> For me drain event is not that critical because there is no loss at the end

There's no loss provided the application doesn't stop/die before the message is published.

> i am more worried about the connection drop because we are storing our financial transaction summary after the payment via rabbitmq, i can stop receiving the new request in case of close event but the already active payment summary will fail to publish.

It sounds like you need a mechanism independent of RabbitMQ to recover from this. Your application could always fail between taking payment and sending the summary.
