### ISSUE TITLE
Why channel.ack takes message type as input instead of just delivery tag 

### ISSUE THREAD

**Issue by shashidhar100** [amqp-node/amqplib#714]
As mentioned in the AMPQ 0 - 9 - 1 [here](https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.ack.delivery-tag) we just need to pass deliveryTag and bit to acknowledge the message but current implementation uses message type, is there any particular reason for this.

**Comment by cressie176** [comment]
Just API choice - you can see [here](https://github.com/amqp-node/amqplib/blob/111225719ea305b7373983fa1a814cdd1ad33a0b/lib/channel_model.js#L209) the deliveryTag being extracted from the message

**Comment by shashidhar100** [comment]
So even if I give other fields as undefined it doesn't make any difference right?

**Comment by cressie176** [comment]
Correct

**Comment by shashidhar100** [comment]
Thank You, for replying fast
