### ISSUE TITLE
Listen for a particular message acknowledgment

### ISSUE THREAD

**Issue by ceessay** [amqp-node/amqplib#715]
I am using amqplib in my Nodejs app for managing rabbitmq. I have publisher and a consumer already setup. I want my consumer to acknowledge messages only on certain conditions. i also want my publisher to be aware of any acknowledgement made by the consumer in order to run some code. Here Is my game plan:

I have the following helper class 
```javascript
const amqp = require('amqplib');

class RabbitMQ {
  constructor(connectionUrl) {
    if (!RabbitMQ.instance) {
      this.connectionUrl = connectionUrl;
      RabbitMQ.instance = this;
    }

    return RabbitMQ.instance;
  }

  async connect() {
    this.connection = await amqp.connect(this.connectionUrl);
    this.channel = await this.connection.createConfirmChannel();
  }

  async createExchange(exchangeName, exchangeType, durable) {
    await this.channel.assertExchange(exchangeName, exchangeType, { durable });
  }

  async createQueue(queueName, durable) {
    await this.channel.assertQueue(queueName, { durable });
  }

  async bindQueue(exchangeName, queueName, routingKey) {
    await this.channel.bindQueue(queueName, exchangeName, routingKey);
  }

  async confirm() {

      return this.channel.confirm();
  }

  async publish(exchangeName, routingKey, message) {
    this.channel.publish(exchangeName, routingKey, Buffer.from(message, "utf8"));
  }


  async consume(queueName, callback) {
    this.channel.consume(queueName, (msg) => {
      callback(msg.content.toString());
      this.channel.ack(msg);
    });
  }

  async ack(message) {
    try {
      this.channel.ack(message);
    } catch (error) {
      console.error(`Failed to acknowledge messages from queue ${queue}`, error);
      throw error;
    }
  }

  

}

module.exports = new RabbitMQ(process.env.RABBITMQ_URL);
```

In order to initiate and publidh on exchanges here is how I do:

```Javascript

const startRabbitMQ = async() => {
    await RabbitMQ.connect();
    await RabbitMQ.createExchange(process.env.RABBITMQ_EXCHANGE_NAME, 'topic');
    console.log("RabbitMQ is connected")

       //....

      await RabbitMQ.createQueue(queueName, { durable: true });
      await RabbitMQ.bindQueue(process.env.RABBITMQ_EXCHANGE_NAME, `${queueName}`, `key.${queueName}`);
      await RabbitMQ.publish(process.env.RABBITMQ_EXCHANGE_NAME, `key.${queueName}`, JSON.stringify(data), options, async (err, ok) => {
        if (err !== null) console.warn('Message nacked!');
        else console.log('Message acked');
      });

}


startRabbitMQ()
```

An this is how I consume the messages 

```javascript
    await RabbitMQ.connect();
    await RabbitMQ.createExchange(process.env.RABBITMQ_EXCHANGE_NAME, 'topic');
    await RabbitMQ.createQueue(queueName, { durable: true });
    await RabbitMQ.bindQueue(process.env.RABBITMQ_EXCHANGE_NAME, queueName, `key.${queueName}`);

    RabbitMQ.consume(queueName, (message) => {
        logger.info(`Received message for `, queueName);
        // logger.info(`Received message for `, queueName, message);

        try {
           //.....
           
            RabbitMQ.ack(message);
        } catch (error) {
            logger.error(error);

        }
    }, { noAck: false });
```

The versions I am using are:
  - RabbitMQ version : 3.8.2
  - amqplib version : 0.10.3
  - Node.js version : 0.10.3

The problem is my publisher is not logging anything. Acknowledgements are not detected.
Any help would be welcome

**Comment by cressie176** [comment]
Hi @ceessay, thank you for your detailed explanation of your problem. 

You may have misunderstood two things...

1. Consumer Acknowledgements
2. Publisher Confirms

### Consumer Acknowledgements
Acknowledgements are between the consumer and the RabbitMQ broker, not between the consumer and the publisher. They tell the broker that is is safe to delete the message from the queue. If you do not acknowledge the message, it will remain in an unacknowledged/unavailable state on the broker until the consumer's channel is closed at which point it will be made available again. If you have set a prefetch limit, this can cause the queue to eventually become blocked. Alternatively if you have not set a prefetch limit, it could cause your node process to eventually run out of memory. It is therefore important to always acknowledge a message, whether explicitly or automatically.

### Publisher Confirms
If you create a channel in confirm mode, RabbitMQ will acknowledge when the message has been safely delivered to all queues, but has nothing to do with when the consumer acknowledges a message. To use this, you must supply a callback to the `channel.publish` method, however your code `this.channel.publish(exchangeName, routingKey, Buffer.from(message, "utf8"));` does not do this.

The best next steps are you to read the RabbitMQ documentation on [consumer acknowledgements and publisher confirms](https://www.rabbitmq.com/confirms.html) and the amqplib [channel api](https://amqp-node.github.io/amqplib/channel_api.html) sections on publishing and consuming. After this, there are a couple of RabbitMQ features which might help...

1. Message Routing
2. RPC

### Message Routing
Can you only route messages to the consumer that need to be processed? If so, using binding keys to filter out unnecessary messages will simplify your consumer code.

### RPC
A common way to signal the publisher from the consumer is to use the [RPC](https://www.rabbitmq.com/tutorials/tutorial-six-python.html) pattern. There is another good article on it [here](https://www.cloudamqp.com/blog/rpc-with-rabbitmq-direct-reply-to.html). You may also want to consider using direct reply to queues.

Good luck!
