### ISSUE TITLE
Nodejs18 support for amqplib

### ISSUE THREAD

**Issue by CHAITANYAMALINENI** [amqp-node/amqplib#719]
I am using amqplib for one of our projects which is running in Nodejs v16 currently. Now we are required to migrate it to Nodejs v18 but amqplib which I am using it as a npm dependency in my project is not supporting Node v18 yet. Could someone please let me know if there are plans to release support for Nodejs 18 and if there is one when it will be released. 

Thanks

**Comment by cressie176** [comment]
Hi @CHAITANYAMALINENI,

Are you having a problem running amqplib with Node 18? The project is tested against [18.1.0](https://github.com/amqp-node/amqplib/blob/main/Makefile#L6) and the [engine](https://github.com/amqp-node/amqplib/blob/main/package.json#L12) specitied in package.json doesn't restrict it either

**Comment by kibertoad** [comment]
We are running amqplib in Node 18 in production, it works fine

**Comment by francescorivola** [comment]
We are also running amqplib latest in Node.js 18.13.0. We haven't found any issue so far, everything smooth.

**Comment by CHAITANYAMALINENI** [comment]
As soon as I upgraded my local to Nodejs18 few days ago, I got error saying createChannel() is not a function something like that. So, I thought it was not supporting 18. But now when I ran it is working fine.

Thank you guys

**Comment by cressie176** [comment]
@CHAITANYAMALINENI,

Sounds like you may have a bug in your application. The only way I can think you would get that error is if the connection object was somehow an instance of a non-connection object - and not null or undefined which would report a 'Cannot read property 'createChannel').

Anyway closing as not an issue with amqplib as far as I can tell
