### ISSUE TITLE
Set a custom header before nack-ing a message

### ISSUE THREAD

**Issue by dimisus** [amqp-node/amqplib#735]
If the above does not help, please provide as much of the following information as is relevant...

  - A clear and concise description of the problem
  - RabbitMQ version - 3.11.10
  - amqplib version - 0.9.1
  - Node.js version - 20+

I desperately want to set a header for a message that is going to be nack'ed. But apparently it is impossible to set a custom header on a message since nack only uses a reference to a message. Is there any work around or any possibility I am not able to find?

What I want to achieve is to set a hint of a reason why the message was nack'ed as a custom header. Which would make debugging and processing of nack'ed message in production much easier and one can react to issues faster. 

If I go the hacky way and publish the messages directly to the DLX I may lose a lot of built-in functionality such as the x-death headers etc.

```javascript
 class MessageBroker ... {

  ...

  nack(id: number | string, queueName: string, reason: string | null = null): void {

    // get the original message from local store
    const originalMessage = this.actives[id];

    // set a header to the message payload
    if (reason && typeof reason === 'string') {
      originalMessage.properties.headers = {
        ...originalMessage.properties.headers,
        'x-nack-reason': reason.substring(0, 63),
      };
    }

    // nack the message using the appropriate channel
    this.channels[queueName].nack(originalMessage, false, dlx);

    delete this.actives[id];
  }


```

**Comment by dimisus** [comment]
Hi. Thank you for the quick reply. Pity...

**Comment by carlhoerberg** [comment]
You can enable transaction on the channel, and then republish the message and ack the original message in a single transaction.

**Comment by dimisus** [comment]
Beg you pardon, but not it is not obvious how to: 

https://amqp-node.github.io/amqplib/channel_api.html

**Comment by cressie176** [comment]
Unfortunately transactions aren't supported with amqplib. There's a discussion [here](https://github.com/amqp-node/amqplib/issues/76#issuecomment-48116102).
