### ISSUE TITLE
No Error emitted when Queue disappears or is deleted

### ISSUE THREAD

**Issue by ssilve1989** [amqp-node/amqplib#736]
Please correct any misunderstanding I may have here, but I have run into the following issue:

When connected to a RMQ Cluster with 3 nodes, it seems that the connection can be on one node, and the queue for that connection exists in another node. These are classic non-mirrored server-named queues. They are non-durable and have auto-delete configured.  If the node that contains the queue disappears, due to either crash/manual restart, the queue disappears, but the connection the client has is fine since it is connected to a different node in the cluster. The problem is nothing is emitted about the queue being gone so the client is in limbo now, not actually subscribed to anything. 

Am I correct in assuming that an error event should be emitted on the Channel allowing for the client to recover?

**RabbitMQ version:**   3.8.34
**amqplib version**: 0.8.0
**Node Version**: 18.14.1

**Comment by cressie176** [comment]
Hi @ssilve1989
I believe the broker should send a [consumer cancel](http://www.rabbitmq.com/consumer-cancel.html) which is delivered to the consumer as a null message

**Comment by ssilve1989** [comment]
Ah perfect, I did see the `null` message. That sounds like useful info that will help resolve the issue here https://github.com/golevelup/nestjs/issues/628

Thanks!
