### ISSUE TITLE
docs: confusing and inconsistent usage of terms "bork", "splode", "close"

### ISSUE THREAD

**Issue by soryy708** [amqp-node/amqplib#742]
In the [channel API docs](https://github.com/amqp-node/amqplib/blob/gh-pages/channel_api.md), some methods are documented as potentially "borking" or "sploding" or "closing" the channel.

Closing the channel with an error is unambiguous, and is clear to non-native English speakers due to its simplicity.

"Bork"/"Borking", which is a slang term roughly synonymous with breaking electronics, is unusual to see in software technical documentation, and non-native speakers get confused over it.

Similarly, "Splode"/"Sploding", which is a slang term synonymous with explosion, is unusual and confusing.

These three terms seem to be used interchangeably in the docs, but it's unclear if there's significance to which term is used. Is borking always the same as sploding and the same as closing?

Examples (emphasis added):

> `assertQueue([queue, [options, [function(err, ok) {...}]]])`
> Assert a queue into existence. This operation is idempotent given identical arguments; however, **it will bork the channel** if the queue already exists but has different properties (values supplied in the arguments field may or may not count for borking purposes; check the borker's, I mean broker's, documentation).

Here we use the form "bork the channel".

> check the borker's, I mean broker's, documentation

This is a cute joke, but it gets in the way of comprehensibility. I think we should stick to just "broker".

> `checkQueue(queue, [function(err, ok) {...}])`
> Check whether a queue exists. **This will bork the channel** if the named queue doesn't exist; if it does exist, you go through to the next round! 

Here we use the form "bork the channel".

> if it does exist, you go through to the next round!

This is a cute joke, which relies on cultural knowledge. This may seem strange to a non-native English speaker. I think we should change it to "if it does exist, nothing happens."

> `assertExchange(exchange, type, [options, [function(err, ok) {...}]])`
> Assert an exchange into existence. As with queues, if the exchange exists already and has properties different to those supplied, **the channel will 'splode**; fields in the arguments object may or may not be 'splodey, depending on the type of exchange.

Here we use the form "channel will splode".

> fields in the arguments object may or may not be 'splodey

It's unclear what does it mean for fields to be 'splodey. I think we should change it to "fields in the arguments object may or may not cause a channel-closing error."

> `deleteQueue(queue, [options, [function(err, ok) {...}]])`
> Delete the queue named. Naming a queue that doesn't exist will result in **the server closing the channel**, to teach you a lesson

Here we use the form "closing the channel".

> to teach you a lesson

Cute, but may be misunderstood as rude. I think it's better to state that the server closes the channel due to error.

> `checkExchange(exchange, [function(err, ok) {...}])`
> Check that an exchange exists. If it doesn't exist, **the channel will be closed** with an error. If it does exist, happy days.

Here we use the form "channel will be closed".

This is in different tense than the previous example. It's unclear if the tense has significance.

> If it does exist, happy days.

Cute, but phatic. I think we should change it to "if it does exist, nothing happens."

> `publish(exchange, routingKey, content, [options])`
> Publish a single message to an exchange. The mandatory parameters are:
> * `exchange` and `routingKey`: the exchange and routing key, which determine where the message goes. A special case is sending `''` (or undefined) as the exchange, which will send directly to the queue named by the routing key; `#sendToQueue` below is equivalent to this special case. If the named exchange does not exist, **the channel will be closed**.

Here we use the form "channel will be closed".

**Comment by cressie176** [comment]
Hi @soryy708,
I'm not in favour of making the changes you propose. It is unlikely that the wording as is will cause significant confusion, and I prefer to keep the original author's humour, style, colloquialisms and character intact.

**Comment by cressie176** [comment]
Hi @soryy708,

You're right, I am a native English speaker. I also work with (and live with) many people who are not. In addition I am familiar with both books you reference and agree both are excellent. Despite this, we still disagree for the need to change the style of language used in the documentation.

**Comment by soryy708** [comment]
Disagreement is good.
Wdyt lets keep this issue open for a while, to check if the community engages?
If there's no interest from the community then I'm ok with closing this issue.

**Comment by omergilad** [comment]
As much as I love programmer humor - when it comes to technical documentation that is critical to implementing systems, and can make the difference between hours or days of research on a platform - 
Documentation should just stick to the point, be 100% neutral and practical in its language, and only serve its main purpose of helping engineers to integrate a system.

Wanna add a separate parody docs section, or a humorous un-wiki styled manual? Go ahead, just separate it from the actual docs please 🙂

**Comment by cressie176** [comment]
> Wdyt lets keep this issue open for a while, to check if the community engages?

I'm happy to leave the issue open for a while, but don't want to give the misleading impression that this is open to vote etc. I see my role on amqplib as a curator of the original authors work - it's still theirs. 

There's a book you might have heard of or read called "Zen and the Art of Motorcycle Maintenance". It explores the relationship between romantic and rational perspectives, arguing that when there is a balance between both, the quality (and even meaning) of life improves. For example, if you view eating food as purely a rational exercise you might only care about nutrition and unquestionably this is more important for sustaining life, however it is the flavour and texture which brings enjoyment, and without this, life would be bland and unfulfilling. Hence I agree with the original author of this work, that there is a place for humour, even in technical documentation.

**Comment by cressie176** [comment]
> Wdyt lets keep this issue open for a while

I'm going to close this now, but when I look at the formatting (see https://github.com/amqp-node/amqplib/issues/741) I'll review the wording at the same time, bearing your points in mind.

> I'm an engineer from Israel,

Also, hope you and your love ones are doing ok.
