### ISSUE TITLE
Feature: Add support for AMQP 0.9.1 "update-secret"

### ISSUE THREAD

**Issue by mortdiggiddy** [amqp-node/amqplib#755]
I have been trying (in vain) to create work around for refreshing the token based access to rabbitmq. I am using rabbitmq 3.12.

The update-secret on the connection was introduced a few years back:
https://rabbitmq.com/amqp-0-9-1-reference.html#connection.update-secret

This allows you to dynamically update your password or OAUTH token without refreshing the connection and channels. This is extremely important when dealing with the rabbitmq_auth_backend_oauth2 plugin that was released, in conjunction with authenticating MQTT clients with the rabbitmq_mqtt and rabbitmq_web_mqtt plugins.

Multiple AMQP clients have implemented this:

- DotNet: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/674
- Java: https://javadoc.io/static/com.rabbitmq/amqp-client/5.15.0/com/rabbitmq/client/AMQP.Connection.UpdateSecret.html
- Pika: https://github.com/pika/pika/pull/1366
- amqp-client.js: https://github.com/cloudamqp/amqp-client.js/blob/ed1fb90/src/amqp-base-client.ts#L108

I am hoping that a developer can add this feature to amqplib. This would aid us greatly because we depend on NestJS, which uses amqplib at the core.

Thank you

**Comment by cressie176** [comment]
Hi @mortdiggiddy,

I'm not getting much time to work on amqplib features at the moment, but if you or anyone else wanted to give it a go, the best starting place would be to familiarise yourself with how amqplib generates the amqp operation definitions.

There's a script called [generate-defs](https://github.com/amqp-node/amqplib/blob/main/bin/generate-defs.js) which is called from the [makefile](https://github.com/amqp-node/amqplib/blob/main/Makefile#L21-L25). This downloads an [old version](https://github.com/amqp-node/amqplib/blob/main/Makefile#L1) of the RabbitMQ code generation spec from before update-secret was added.

You could try updating the makefile to download the latest spec is [here](https://github.com/rabbitmq/rabbitmq-server/blob/v3.12.13/deps/rabbitmq_codegen/amqp-rabbitmq-0.9.1.json) and see if the tests still pass, then work out how to add the updateSecret method to the [callback model](https://github.com/amqp-node/amqplib/blob/bbe579e467866a40ff1c0ae2428c416111340364/lib/callback_model.js) and [channel model](https://github.com/amqp-node/amqplib/blob/bbe579e467866a40ff1c0ae2428c416111340364/lib/channel_model.js).

**Comment by cressie176** [comment]
Correction, I think the updateSecret needs to be added to the [connection class](https://github.com/amqp-node/amqplib/blob/bbe579e467866a40ff1c0ae2428c416111340364/lib/connection.js) rather than the channel / callback models

**Comment by cressie176** [comment]
Hi @mortdiggiddy,

I've added an updateSecret method to both the callback and promise apis on [this](https://github.com/amqp-node/amqplib/tree/connection-update-secret) branch. Are you able to confirm works as you expect please?

```
await connection.updateSecret(Buffer.from('new secret'), 'some reason');
```

Because update-secret is a RabbitMQ extension you don't WireShark decodes both the operation and reply as Connection.Unknown

**Comment by cressie176** [comment]
Any luck with the testing @mortdiggiddy?

**Comment by mortdiggiddy** [comment]
So far so good, a few more test and I will update this.

**Comment by cressie176** [comment]
Any more updates @mortdiggiddy?

**Comment by cressie176** [comment]
@mortdiggiddy?

**Comment by mortdiggiddy** [comment]
Stephen,

Apologies for the delayed response. I have tested this in an isolated environment, and created a branch to update AmqpConnectionManager (https://github.com/jwalton/node-amqp-connection-manager),

This is working as expected. I have also tested the ability to send a JWT as the password using the rabbitmq-oauth2 plugin. This is working, the TTL shown in the debug logs of a running RabbitMQ 3.13-management container shows the updated expiration countdown. 

I will now ask the code owner of AmqpConnectionManager to update his code as well inside this class:
https://github.com/jwalton/node-amqp-connection-manager/blob/master/src/AmqpConnectionManager.ts

I will also be reaching out to the NestJS developers to allow for the same inside these classes:

https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-rmq.ts
https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-rmq.ts

https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-mqtt.ts
https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-mqtt.ts

**Comment by mortdiggiddy** [comment]
@cressie176 Will the 'generate defs' be updated to the new amqplib protocol as well? I am guessing this is how the ./defs class is generated. I forgot to ask how this will be updated once you merge the changes.

**Comment by cressie176** [comment]
Yes, they'll be updated. Currently the process is to checkout from the tag to a clean directory, then test, build and publish. I want to change this so the defs are added to source control, and automate the release process. I might have a go at that next.
