### ISSUE TITLE
501 (FRAME-ERROR) - after indeterminate amount of large messages

### ISSUE THREAD

**Issue by GlennButera** [amqp-node/amqplib#757]
## Description

When using RabbitMQ to send payloads (that are our internal software events) that are `4.3MB` and `8.6MB` every 10 seconds, after a few minutes there begins to be intermittent errors coming from connected channels consuming these payloads.  It appears to be random which channels have the issues and when they happen, but the FRAME-ERROR is always the error from the channel "error" event:

> Connection closed: 501 (FRAME-ERROR) with message "FRAME_ERROR - type 3, first 16 octets

The code that we are using to send these payloads are as follows with the `checkBlocked` method being a lightweight check for server resource constrictions and `checkPacketSize` ensuring that the packet is not larger than the 128MB RabbitMQ Inter-node Communication Buffer Size Limit.

```
  async sendMessageToEventQueue(_packet, _options = null) {
    this.checkBlocked();

    if (this.disabled) {
      return;
    }

    if (this.channel) {
      checkPacketSize(_packet, this.source);
      try {
        const ttlHeader =
          this.deduplicationSettings.cacheTtl !== undefined
            ? { 'x-cache-ttl': this.deduplicationSettings.cacheTtl }
            : {};

        const headers = _options && _options.headers ? { ...ttlHeader, ..._options.headers } : ttlHeader;

        const options = {
          ..._options,
          headers,
        };

        return this.channel.publish('event_exchange', '', Buffer.from(JSON.stringify(_packet)), options);
      } catch (err) {
        logRMQMessage(err);
      }
    }
  }
```

## RabbitMQ Version

`3.13.0`

## amqplib Version

`0.10.3`

## NodeJS Version

`18.17.1`

## Stack Trace

```
Error: Connection closed: 501 (FRAME-ERROR) with message "FRAME_ERROR - type 3, first 16 octets = <<"                ">>: {invalid_frame_end_marker,
                                                   46}"
    at Object.accept (/Users/glennbutera/Environments/2023.1/iap/node_modules/@itential/network/node_modules/amqplib/lib/connection.js:90:15)
    at Connection.mainAccept (/Users/glennbutera/Environments/2023.1/iap/node_modules/@itential/network/node_modules/amqplib/lib/connection.js:63:33)
    at Socket.go (/Users/glennbutera/Environments/2023.1/iap/node_modules/@itential/network/node_modules/amqplib/lib/connection.js:486:48)
    at Socket.emit (node:events:514:28)
    at emitReadable_ (node:internal/streams/readable:590:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

**Comment by cressie176** [comment]
Hi @GlennButera,

I haven't come across this before, but other RabbitMQ issues I've found online suggest this problem can occur when publishing from different threads using the same channel. If I understand correctly, a message published by one thread is being mutated by another thread before it is sent, invalidating it.

While Node.js isn't multithreaded, you can get this behaviour when sharing data between asynchronous code. You're using JSON.stringify to serializse `_packet` so I believe that might be safe, however you passing in `_options`, so potentially that is being mutated. Can you try deep cloning this before immediately so that neither it, or the headers sub-document have any chance to be mutated?

**Comment by cressie176** [comment]
You could also try not sharing the channel. This will be a little slower though.

**Comment by GlennButera** [comment]
@cressie176 I have tried "deep cloning" the `_options` immediately wherever it was being used by doing a `JSON.parse(JSON.stringify(_options));`.  The issue still occurred.

**Comment by cressie176** [comment]
Hi @GlennButera,
I've created what I hoped would be a [minimal reproducible example](https://github.com/cressie176/amqplib-725) based on your description of the problem, but it works fine. Are you able to fork this, test it in your environment, and make the necessary amends to reproduce the frame error please?

**Comment by cressie176** [comment]
Any update @GlennButera?

**Comment by GlennButera** [comment]
@cressie176 My apologies, we were not able to reproduce with the minimal reproducible example.  We have decided to move on from the issue and are going about a different solution that will remove this issue from our code by not leveraging RabbitMQ in the same way.
