### ISSUE TITLE
Emits a acknowledge event.

### ISSUE THREAD

**Issue by titsex** [amqp-node/amqplib#759]
How can I guarantee knowledge?

I definitely need to wait for the acknowledgment before executing the subsequent code.

At the moment, I am solving this problem as follows:
```typescript
const channel = ...

channel.ack()

setTimeout(() => {
    // my code
}, 0)
```

I would like to expect the following behavior:
```typescript
const channel = ...

channel.on('ack', () => {
    // my code
})

channel.ack()
```

**Comment by cressie176** [comment]
Ravan, please change your username to something more appropriate if you wish to receive help with this library
