### ISSUE TITLE
Error: Unexpected close at succeed

### ISSUE THREAD

**Issue by y-nk** [amqp-node/amqplib#761]
First and foremost, I'm sorry for yet another of these issue.

Secondly, I have found the comment in #151 but could not find an answer for what i'm trying to achieve.

## Problem

Thread hangs exactly 30s after `await channel.close()` was called.

## Context

I'm running integration tests and I'd like the connection to be closed when i end them. For this reason I have disabled heartbeats in rabbitmq (passing `heartbeat=0` in conf and confirmed it is loaded from docker image logs), and added `?heartbeat=0` on the client side and also confirmed that heartbeat is disabled by logging `.heartbeat` and `.heartbeater` after calling `connect()`.

## Testing

I have fenced the `await channel.close()` call to log the client side process, as well as open the server logs to trace the testing connection.

the interesting code is:

```js
    // somewhere earlier, deep in the application code, an equivalent of
    const channel = await amqplib.connect('amqp://localhost:5672?heartbeat=0')
```

```js
    // in my test file
    process.on('uncaughtException', err => {
      console.log('uncaught', new Date(), { err })
      process.exit(1)
    })

    try {
      console.log('heartbeat', channel.connection.heartbeat)

      console.log('before', new Date())
      await channel.close() // ← imported properly from the 1st snippet
      console.log('after', new Date())
    } catch (err) {
      console.log('error', new Date(), err)
    }
```

1. the process listener never gets called

2. the log looks like this:

```
RUNS  test/debug.e2e-spec.ts
  console.log
    heartbeat 0

      at Object.<anonymous> (debug.e2e-spec.ts:118:15)

  console.log
    before 2024-05-03T06:27:33.122Z

      at Object.<anonymous> (debug.e2e-spec.ts:120:15)

  console.log
    after 2024-05-03T06:27:33.128Z

      at Object.<anonymous> (debug.e2e-spec.ts:122:15)

 PASS  test/debug.e2e-spec.ts
  Auth flow (e2e)
    ✓ run blank (201 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.323 s, estimated 3 s
Ran all test suites matching /debug/i.
Jest did not exit one second after the test run has completed.

'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
node:events:509
    throw err; // Unhandled 'error' event
    ^

// EXACTLY 30s have passed here (down to 100ms)

Error: Unhandled error. (Error: Unexpected close
    at succeed
```

I want to stress that i have other components running for this integration tests so `--forceExit` is not an option ; i also can't let the connection like that because the integration test rebuilds the whole application at `beforeEach`, which means several connections should spawn (and so the 30s mess would pile up).

I've no clue of why, but i'm definitely willing to try anything suggested.

Thank you for time and patience.

**Comment by cressie176** [comment]
Hi @y-nk

If I understand correctly you are writing unit tests, and after the suite completes the test process is waiting instead of existing cleanly, this indicating that there is either some asynchronous process remaining in the event loop, or that there is a connection that hasn't been closed. Then 30 seconds later the uncaught exception handler receives an unexpected close error. This is a surprise because you have disabled heartbeats.

There are a few things to try.

1. You don't mention that you are closing the connection to the RabbitMQ server. You will need to do this otherwise the tests will not exit
2. Use [wireshark](https://www.rabbitmq.com/amqp-wireshark) to inspect the traffic between your machine and the RabbitMQ broker. This will show the initial handshake where the heartbeat is agreed, any heartbeat operations sent between client and server, the channel open and close operations, and also connection open and close operations.

**Comment by y-nk** [comment]
1. looking at the amqplib it seems that what i mentioned earlier (`await channel.close()`) closes the connection. the object returned by `amqplib.connect` is a `ChannelModel` and its `close` implementation is a promisified call to its own `conn` property.

2. i'm thinking to go this road but i wanted to make sure i didn't miss something obvious, hence this post.

**Comment by y-nk** [comment]
@cressie176 I still need further investigation but my findings so far suggest that closing the connection before the end of the handshake would be the result of this issue. i'm thinking that because even tho i'm calling `channel.close()` which causes the conn to disconnect, the `succeed` // `onOk` still trigger, and that's part of the opening handshake (if i'm not mistaken). i'm still relatively new to the amqp protocol so i'm not sure about this, but the callstack and the error i have both suggest so.

**Comment by cressie176** [comment]
@y-nk sorry to say, but I think you've missed something in your investigation. I'm certain channel.close does not directly close the connection - it wouldn't make any sense since connections can have multiple channels. If you use wireshark you will the commands that are exchanged between client and server.

**Comment by cressie176** [comment]
Missed this earlier...

```
const channel = await amqplib.connect('amqp://localhost:5672?heartbeat=0')
```

This does not create a channel. This is a connection. To create a channel you need to do

```
const connection = await amqplib.connect('amqp://localhost:5672?heartbeat=0')
const channel = await connection.createChannel() // or connection.createConfirmChannel()
```

**Comment by y-nk** [comment]
Sorry also, my var name was confusing. `connect` seems to return a `ChannelModel` rather than a channel.

i was spotting those:

1. https://github.com/amqp-node/amqplib/blob/main/channel_api.js#L10
2. https://github.com/amqp-node/amqplib/blob/main/lib%2Fchannel_model.js#L25-L27

**Comment by cressie176** [comment]
I don't think the amqplib names for ChannelModel and CallbackModel are particularly helpful. You can think of them as objects which wrap the raw connection, and whose job is to obtain channels. Consequently it is typical to name the object returned from `amqplib.connect()` a `connection` (or`conn` if you prefer abbreviations) and then name the object returned from `connection.createChannel()` or `connection.createConfirmChannel()` a channel.

**Comment by y-nk** [comment]
complete stacktrace seems to tell that the handshake still continues its way even tho the `channelModel.close()` was called, awaited and completed.

I have first the logs around the `await channelModel.close()` with timestamps shown, _then_ a 30s delay, _then_ the error with this stacktrace:

```
Error: Unhandled error. (Error: Unexpected close
    at succeed (~/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/connection.js:280:13)
    at onOpenOk (~/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/connection.js:262:5)
    at ~/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/connection.js:165:32
    at ~/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/connection.js:159:12
    at Socket.recv (~/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/connection.js:507:12)
    at Object.onceWrapper (node:events:632:28)
    at Socket.emit (node:events:518:28)
    at emitReadable_ (node:internal/streams/readable:832:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21))
    at Connection.emit (node:events:507:17)
    at Connection.Object.<anonymous>.C.onSocketError (~/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/connection.js:361:10)
```

That particular `at onOpenOk` makes me think the opening handshake is still ongoing despite the connection being closed.

**Comment by y-nk** [comment]
I have tried a minimal reproduction case with exactly the above ↑ and it works as expected. I will keep this open just for updating but i can now confirm the issue lives in some of the app code layers which i must look into.

**Comment by cressie176** [comment]
Just FYI

With the following code & rabbitmq configured to disable heartbeats...

```js
const amqp = require('amqplib');

(async () => {
  const connection = await amqp.connect('amqp://localhost:5672?heartbeat=0');
  await connection.close();
})();
```

this is what you would see with Wireshark

<img width="1792" alt="Screenshot 2024-05-04 at 09 03 04" src="https://github.com/amqp-node/amqplib/assets/229672/5ba86912-f0e5-4de8-9272-d5e0f65aa9e1">

<img width="1792" alt="Screenshot 2024-05-04 at 09 02 57" src="https://github.com/amqp-node/amqplib/assets/229672/cff88515-1929-40e9-b308-777d435a35c0">

**Comment by y-nk** [comment]
@cressie176 thanks a lot for this :) i'm sure these screenshots are quite cumbersome to produce, really appreciate it.

**Comment by y-nk** [comment]
I have dug inside the deep abysses of our backend code, and found some wrapper (as a package) around amqplib **and found the answer.** 

@cressie176 i'm grateful for the time spent and sorry it was on my end. Thanks a lot for your time and if i give a little of mine, that's more than ok.

### So, what happened

the wrapper does:

1. creates a connection _(i'll name it channelModel to avoid confusion with the Connection object)_ using `connect` from `amqplib
2. creates a channel with approximately `const channel = await channelModel.createChannel()`
3. calls `await channel.assertExchange()` with the exchange name

... and add a bunch of listeners.

```ts
  channelModel.on('error', (error: Error): void => errorHandler(error))
  channelModel.on('close', (): void => errorHandler(new Error('RabbitMQ connection has been closed')))
  channelModel.on('blocked', (): void =>
    errorHandler(new Error('RabbitMQ connection has been blocked')),
  )

  channel.on('error', (error: Error): void => errorHandler(error))
  channel.on('close', (): void => errorHandler(new Error('RabbitMQ channel has been closed')))

  return { channel, name: exchangeName }
```

↑ this is 100% extracted from our codebase.

I had some hint when i started to comment the channel close listener, which removed the bug.

I had to discover that the `errorHandler` is a userland callback which is supposed to help deciding what to do with the internal amqplib errors (ie: logging for prod server). but some smart ass implemented it as `(err) => { log(err); throw err; }`

Which means... when i call `await channelModel.close()`, it will close the connection, fire the `close` event, and throw an error to the main thread.

## Minimal reproduction case

```ts
import { connect } from 'amqplib'

function errHandler(err: string) {
  console.log(err)
  throw err // comment this for "it's working"
}

async function main() {
  console.log('---')
  console.log(new Date(), 'connect')
  const cm = await connect('amqp://localhost:5672?heartbeat=0')
  console.log(new Date(), 'connected')

  console.log(new Date(), 'create channel')
  const chn = await cm.createChannel()
  console.log(new Date(), 'channel created')

  await chn.assertExchange('pubsub', 'topic')

  cm.on('error', () => errHandler('cm err'))
  cm.on('close', () => errHandler('cm close'))
  cm.on('blocked', () => errHandler('cm blocked'))

  chn.on('error', () => errHandler('chn err'))
  chn.on('close', () => errHandler('chn close'))

  console.log(new Date(), 'disconnect')
  await cm.close()
  console.log(new Date(), 'disconnected')
}

main()
```

log **with** the `throw`:

```
---
2024-05-04T09:05:12.947Z connect
2024-05-04T09:05:12.970Z connected
2024-05-04T09:05:12.970Z create channel
2024-05-04T09:05:12.973Z channel created
2024-05-04T09:05:12.975Z disconnect
chn close
cm err
'cm err'
```

log **without** the `throw`:

```
---
2024-05-04T09:09:32.635Z connect
2024-05-04T09:09:32.662Z connected
2024-05-04T09:09:32.662Z create channel
2024-05-04T09:09:32.665Z channel created
2024-05-04T09:09:32.666Z disconnect
chn close
cm close
2024-05-04T09:09:32.669Z disconnected
```

We can see that when the error is thrown, the `disconnected` log is never printed. As why it translates to a 30s delay, i don't know. My intuition tells me it's related to jest since the code runs in a controlled environment (with `afterEach()`).

What a great day.

**Comment by cressie176** [comment]
Glad you got to the bottom of it @y-nk.
