### ISSUE TITLE
Typo in the example code 

### ISSUE THREAD

**Issue by ipython3** [amqp-node/amqplib#762]
In [https://amqp-node.github.io/amqplib/](https://amqp-node.github.io/amqplib/), there is a section explaining "**Why does amqplib crash my application?**". I believe that there is a typo in the example code:

```javascript
const connection = await amqplib.connect();
connection.on('error', (err) => {
  // recover or exit
});

const channel = await connection.createChannel();
channel.on('error', (err) => {
  // recover or exit
})l
```

The `l` character in the end should be a semicolon.

Thank you for creating this easy-to-use library!

**Comment by cressie176** [comment]
Thanks @ipython3. I've fixed the docs.
