### ISSUE TITLE
Who calls accept()?

### ISSUE THREAD

**Issue by deostroll** [amqp-node/amqplib#763]
I am trying to determine if the following function is called multiple times, or, only once, in an eventloop tick.

https://github.com/amqp-node/amqplib/blob/64d1c1ec19afa64a7ec5c355ea7620f0b227fb30/lib/channel.js#L289

I assume this is the function which processes messages and finally ends up calling the callback fn passed to the channel.consume() api.

**Comment by cressie176** [comment]
I believe It is called [once per frame](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L434) received from the RabbitMQ broker. Multiple frames can be received within one tick of the event loop

**Comment by deostroll** [comment]
So there is a possibility for the deliver event to be fired multiple times within an eventloop tick?
