### ISSUE TITLE
first error message thrown by stream_socket_enable_crypto() is not propagated to caller

### ISSUE THREAD

**Issue by jjdunn** [amqp-node/amqplib#765]
steps to create the problem:
 1. in php.ini, set open_basedir to a list of directories which includes the application, but does _not_ include the path to SSL certificate and associated information (intermediate cert, keys, etc)
 2. attempt to open an AMQPS connection
 3. get the error "stream_socket_enable_crypto(): Unable to get real path of certificate file...."

the problem is that TWO errors are thrown by the call to ```stream_socket_enable_crypto()``` in \Wire\IO\StreamIO::enableCrypto() ,  but only the __second__ error is reporter to the caller, which makes debugging harder than necessary.

  1. the first error is "stream_socket_enable_crypto(): open_basedir restriction in effect..." which is helpful.  This is the real cause of the problem; but this error is NOT reported to the caller.  it gets overwritten by the second error:
  2. the second error is "unable to get real path of certificate file...." which is true; but not easy to debug

see attached screenshots:
1. stack trace at \Wire\IO\StreamIO::enableCrypt()
2. stack trace at \Wire\IO\StreamIO::error_handler()
3. StreamIO properties in first call to error_handler(), showing the error message which gets lost
4. StreamIO properties in the second call to error_handler(), showing the less-valuable error message which is propagated to caller

context: 
 * Windows Server 2019
 * apache httpd 2.4.59
 * PHP 8.3.7 x64
 * PhpAmqpLib  3.6.2
 
![StreamIO-EnableCrypto-stackTrace](https://github.com/amqp-node/amqplib/assets/333222/ed1d4b24-8302-46be-b867-31603ad838d5)
![StreamIO-EnableCrypto-stackTrace-2](https://github.com/amqp-node/amqplib/assets/333222/965375a3-d388-4594-8388-e411c3e5b3f6)
![StreamIO-errorHandler-1](https://github.com/amqp-node/amqplib/assets/333222/4ea38625-831d-4a7b-9f08-2cdac5b26173)
![StreamIO-errorHandler-2](https://github.com/amqp-node/amqplib/assets/333222/5f62a84f-251e-4557-8558-d414e7bc0586)

**Comment by jjdunn** [comment]
p.s. the issue reported in this ticket was not exposed in PHP 8.1.x and preceding versions

the ```open_basedir``` check when referencing local_cert and local_pk in was introduced in PHP 8.2:
https://github.com/php/php-src/issues/9310

**Comment by jjdunn** [comment]
My proposed solution for this issue would be for \Wire\IO\AbstractIO::error_handler() to accumulate an array of errors (instead of just _last_error_); and ::throwOnError() would report the list of errors.   I guess AbstractIO::last_error should be renamed as _error_list_ or _errors_ or similar.  If you agree with this solution-design I would be happy to submit a PR...let me know.

**Comment by cressie176** [comment]
@jjdunn this is a JavaScript project. I think you probably want https://github.com/php-amqplib/php-amqplib

**Comment by jjdunn** [comment]
> @jjdunn this is a JavaScript project. I think you probably want https://github.com/php-amqplib/php-amqplib

very sorry for the unwanted comments.  you are perfectly correct.  I will move the issue to that project.

**Comment by cressie176** [comment]
@jjdunn no need to apologise, no harm done
