### ISSUE TITLE
Missing x-consumer-timeout

### ISSUE THREAD

**Issue by TzachiSh** [amqp-node/amqplib#767]
### Description
The x-consumer-timeout parameter is missing.

Per-queue Delivery Timeouts Using an Optional Queue Argument
Set the x-consumer-timeout [optional queue argument](https://www.rabbitmq.com/docs/queues#optional-arguments) on a queue when the queue is declared. The timeout is specified in milliseconds. Whether the timeout should be enforced is evaluated periodically, at one minute intervals.

**Comment by cressie176** [comment]
Hi @TzachiSh, you can specify queue arguments as follows...

```
let options = {
  arguments: {
    'x-consumer-timeout': value
  }
}

channel.assertQueue(queueName, options
```
