### ISSUE TITLE
I would like to check the existence of an exchange without the closing the channel in failure cases

### ISSUE THREAD

**Issue by Paul-Lazunko** [amqp-node/amqplib#769]

**Comment by cressie176** [comment]
Hi @Paul-Lazunko,

I assume you mean that you would like to check for the existence of an exchange, but not error if the exchange does not exist or has different parameters.

This is supported by the AMQP protocol, and therefore not possible with amqplib. One option outside of this module is to install the RabbitMQ management plugin and use the RESTful API.

**Comment by Paul-Lazunko** [comment]
Firstly, sorry for the incomplete issue description. I will try to correct it.

You are right, the server is the one closing the connection in such cases, and it is definitely not amqplib. 
Overall, I am very satisfied with your library and have been using it for many years.

My request is more about how to work around these server-side behavior specifics. Since the method checkExchange is not safe as it can lead to a disconnect and disrupt the normal operation of the system (which we always try to avoid, even if the system is quite prepared for such scenarios), you can use assertExchange with the { passive: true } in the options.
This avoids a disconnect if the exchange doesn't exist, but this operation, unlike the check, is not idempotent since the exchange may be created created, and most importantly, if the settings do not match, there will be another error and a disconnect.
Actually, I work around this with the following solution: in addition to the main connection, I use an additional connection and channel (which can also be a pool) for such checks, and the loss of connection in this case does not affect the main channel through which communication occurs.

Perhaps you are working on implementing a similar solution. 
Even if not, the idea of using the management plugin and API is quite sound.
Thank you!

**Comment by cressie176** [comment]
Hi @Paul-Lazunko,

In the applications I work on, I don't need dynamic queues / exchanges. On start-up each publisher assets to exchanges it needs, and each consumer asserts the queues (and applies the bindings). This ensures the applications have the RabbitMQ objects they need when they are first deployed to a new environment, and on restart. The latter should not be necessary though as it's highly unlikely anyone will have deleted or redefined the queues / exchanges.
