### ISSUE TITLE
Published messages does not appear in queue

### ISSUE THREAD

**Issue by maxime-aubry** [amqp-node/amqplib#770]
I have a NestJS project with WSL and docker.
Callback endpoint is not fired each time a publish a message in queue.

Here is docker-compose.yml file
``` YAML
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - './env/.env.local'
```

Here my message queue module for the api what send message :
``` Typescript
import { EnvironmentConfigModule } from '@app/shared/config/environment-config/environment-config.module';
import { EnvironmentConfigService } from '@app/shared/config/environment-config/environment-config.service';
import type { IMessageQueueConfiguration } from '@app/shared/config/environment-config/message-queue-config.interface';
import { type DynamicModule, Module, type Provider } from '@nestjs/common';
import { ClientProxyFactory, Transport } from '@nestjs/microservices';
import { MessageQueueService } from './messageQueue.service';

@Module({
  imports: [EnvironmentConfigModule],
  providers: [MessageQueueService],
  exports: [MessageQueueService],
})
export class MessageQueueModule {
  static registerRmq(service: string, queue: string): DynamicModule {
    const providers: Provider[] = [
      {
        provide: service,
        useFactory: (config: IMessageQueueConfiguration) => {
          return ClientProxyFactory.create({
            transport: Transport.RMQ,
            options: {
              urls: [config.getMessageQueueUrl()], // amqp://user:password@localhost:5672
              queue,
              queueOptions: {
                durable: true, // queue survives broker restart
              },
            },
          });
        },
        inject: [EnvironmentConfigService],
      },
    ];

    return {
      module: MessageQueueModule,
      providers,
      exports: providers,
    };
  }
}
```

here is the message queue service for the api what receives the message :
``` Typescript
import { EnvironmentConfigService } from '@app/shared/config/environment-config/environment-config.service';
import type { IMessageQueueConfiguration } from '@app/shared/config/environment-config/message-queue-config.interface';
import type { IMessageQueueService } from '@app/shared/interfaces/services/messageQueue/messageQueue.service.interface';
import { Inject, Injectable } from '@nestjs/common';
import { type RmqContext, type RmqOptions, Transport } from '@nestjs/microservices';

@Injectable()
export class MessageQueueService implements IMessageQueueService {
  constructor(@Inject(EnvironmentConfigService) private config: IMessageQueueConfiguration) {}

  public getMessageQueueOptions(queue: string): RmqOptions {
    return {
      transport: Transport.RMQ,
      options: {
        urls: [this.config.getMessageQueueUrl()], // amqp://user:password@localhost:5672
        noAck: false,
        queue,
        queueOptions: {
          durable: true, // queue survives broker restart
        },
      },
    };
  }

  public acknowledgeMessage(context: RmqContext): void {
    const channel = context.getChannelRef();
    const message = context.getMessage();
    channel.ack(message);
  }
}
```

Here is the controller to send the message :
``` Typescript
import { Controller, Get, Inject } from '@nestjs/common';
import type { ClientProxy } from '@nestjs/microservices';
import type { Observable } from 'rxjs';

@Controller()
export class ApiController {
  constructor(@Inject('AUTH_SERVICE') private readonly authService: ClientProxy) {}

  @Get('getUser')
  public getUser(): Observable<any> {
    return this.authService.send(
      {
        cmd: 'get-user',
      },
      {},
    );
  }
}
```

Here is the controller to receive the message :
``` Typescript
import type { IMessageQueueService } from '@app/shared/interfaces/services/messageQueue/messageQueue.service.interface';
import { MessageQueueService } from '@app/shared/services/messageQueue/messageQueue.service';
import { Controller, Inject } from '@nestjs/common';
import { Ctx, MessagePattern, type RmqContext } from '@nestjs/microservices';

@Controller()
export class AuthController {
  constructor(@Inject(MessageQueueService) private readonly messageQueueService: IMessageQueueService) {}

  @MessagePattern({ cmd: 'get-user' })
  public getUser(@Ctx() context: RmqContext): string {
    this.messageQueueService.acknowledgeMessage(context);
    return 'test';
  }
}
```

When i run the sender, i get this log :
`
[Nest] 15911  - 10/08/2024, 11:40:17 AM     LOG [Incoming Request on /getUser] [INFO] method=GET ip=::1
[Nest] 15911  - 10/08/2024, 11:40:17 AM   ERROR [End Request for /getUser] [ERROR] method=GET status=500 code_error=null message=undefined
`

When i run the receiver, i get this log :
`
[Nest] 15681  - 10/08/2024, 11:40:17 AM    WARN [Server] An unsupported message was received. It has been negative acknowledged, so it will not be re-delivered. Pattern: {"cmd":"get-user"}
`

In RabbitMQ web interface, i can see that my user has all rights ".*".
Your can download my project [here](https://github.com/maxime-aubry/shadow-hunters-web-api/tree/feature/2_create_auth_microservice).

What could be the problem in my project ?

thanks.

**Comment by cressie176** [comment]
Hi @maxime-aubry,

Thank you for taking the time to put together such a well documented issue. My guess is that this isn't a RabbitMQ or amqplib problem though. Instead, the fact that Nest is logging that an unsupported message was received, and that it was negatively acknowledged indicates a message was published and consumed correctly, but rejected in the NestJS code.

You can find the NestJS message template for this warning [here](https://github.com/nestjs/nest/blob/master/packages/microservices/constants.ts#L48-L52). This is used [when no handler is found for a particular pattern](https://github.com/nestjs/nest/blob/9825529f405fa6064eb98d8ecb2a5d3d5f1e41f9/packages/microservices/server/server-rmq.ts#L192-L196).

I am not familiar with NextJS so can't help with how to resolve this.

**Comment by maxime-aubry** [comment]
Thanks.

So i will publish that on NestJS support.

**Comment by cressie176** [comment]
You might also try using [wireshark](https://www.rabbitmq.com/amqp-wireshark) to see the messages being published and delivered. It's pretty easy to get working and interesting if you are curious about the amqp protocol

**Comment by maxime-aubry** [comment]
actually, this bug is due to a malfunction between amqp and Bun.
do you have a solution ?

**Comment by cressie176** [comment]
> actually, this bug is due to a malfunction between amqp and Bun.

I would avoid Bun. One look at the issues list tells you it's not even close to production ready.

You might want to start with [this one](https://github.com/oven-sh/bun/issues/5627#issuecomment-2302934448)

**Comment by cressie176** [comment]
In case I confused you, I didn't mean to suggest https://github.com/oven-sh/bun/issues/5627 will fix your connection issue. I suspect that's config. However, even if you do manage to connect, you're likely to run into a host of unresolved problems if you persist in using Bun.
