### ISSUE TITLE
update docs about global prefetch (qos) deprecation

### ISSUE THREAD

**Issue by soryy708** [amqp-node/amqplib#771]
The [channel.prefetch docs](https://amqp-node.github.io/amqplib/channel_api.html#channel_prefetch)
currently have a note about using global Prefetch on RabbitMQ v3.3.0 or below,
but don't say anything about RabbitMQ 4.0 or above.

Global QoS has been deprecated, as seen in RabbitMQ 4.0 Deprecation Announcements:

> **Why are we making this decision?**
> Global QoS, where a single shared prefetch is used for an entire channel, is not recommended practice.
> **What alternatives exist?**
> Per-consumer QoS (non-global) should be set instead.

https://www.rabbitmq.com/blog/2021/08/21/4.0-deprecation-announcements#removal-of-global-qos

Continuing with the existing behavior of the documentation, describing the nuances about differences between RabbitMQ versions, I believe that the docs need to include:

- Global Prefetch has been deprecated in RabbitMQ 4.0.
- It will continue to work, but show a banner about "Deprecated features are used"
- In a future version of RabbitMQ, which isn't known yet, the feature will be removed and stop working

**Comment by cressie176** [comment]
Agree. Thanks @soryy708

**Comment by cressie176** [comment]
Done
