### ISSUE TITLE
Update information link provided while connecting

### ISSUE THREAD

**Issue by 4strodev** [amqp-node/amqplib#779]
It's not a bug, but the link provided while establishing the amqp connection is an old one, and it's not broken thanks to the GitHub pages redirection. But it's an easy change to update the link to the current webpage https://amqp-node.github.io/amqplib/

**Comment by cressie176** [comment]
Hi @4strodev, thanks for reporting this. I assume you mean the "https://github.com/squaremo/amqp.node/" link?

I can see a [few of places](https://github.com/search?q=org%3Aamqp-node+%22https%3A%2F%2Fgithub.com%2Fsquaremo%2Famqp.node%2F%22&type=code) it's still referenced, but not sure they're the same as the ones you were referring to?

**Comment by 4strodev** [comment]
Specifically, this happens on the [connect.js](https://github.com/amqp-node/amqplib/blob/main/lib/connect.js) file. As you could see, an object is declared with the metadata that is going to be sent. In this case, the information link. I didn't notice that places that you gave to me :sweat_smile:

**Comment by cressie176** [comment]
Thank you

**Comment by cressie176** [comment]
I've updated the links
